### ISSUE TITLE
Roadmap: simplify and clarify run-on sentence

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/about#1007]
"While widespread, global membership is the long-term goal of the Foundation, we recognize that, for public organizations, the hurdles to making such a commitment are significant."

@clausmullie wrote "Consider simplifying this sentence - the commas make it a bit difficult to read"

**Comment by Ainali** [comment]
How about splitting it into two sentences?
"Membership of globally widespread public organizations is the long-term goal of the Foundation. However, we recognize that the hurdles for them to make such a commitment are significant."
