### ISSUE TITLE
Feedback on our codebase types list

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1013]
In our blog post [Types of codebases to strategically steward](https://blog.publiccode.net/news/2021/11/08/types-of-codebases-to-strategically-steward.html) we showed our draft of codebase types that we want to directly steward in the long-term. We asked you to give your feedback here. You can use the thumbs up emoji to indicate that you like our draft. If you don't like it for some reason or if you want to add or remove types from the list, please leave a comment so that we can understand how you want it to improve.

**Comment by sharifX** [comment]
Great list. Along with Climate change I would also add Environmental sciences and biodiversity.  A few others: 
1. Public transportation (beyond Open Data portals; there are routing and traffic control systems) 
2. Along the lines of public record -- long term data archival 
3. Community/decentralized social network tools (thinking about projects like https://matrix.org/, mastodon).

**Comment by Ainali** [comment]
> 1. Public transportation (beyond Open Data portals; there are routing and traffic control systems)
> 2. Along the lines of public record -- long term data archival
> 3. Community/decentralized social network tools (thinking about projects like https://matrix.org/, mastodon).

Thank you @sharifX! 1 is a great addition, and 2 was meant to be included in my cryptic "Something for public records / minutes / archive / freedom of information portal?" and I admit I didn't do a great job in explaining that. I'll make sure that next version has more clarity on it, because I agree that is an important point.

For 3, is that something that you think should be run by public organizations? For me, it is not obvious that they would connect to public policy, but I might miss what you are thinking they should be used for.

**Comment by sharifX** [comment]
` For 3, is that something that you think should be run by public organizations? For me, it is not obvious that they would connect to public policy, but I might miss what you are thinking they should be used for.
`
I am thinking about the idea of a "Digital Public infrastructure" (see https://knightcolumbia.org/content/the-case-for-digital-public-infrastructure by Ethan Zuckerman) where communication tools such as social networking, chat software etc are run not by big tech but by the communities themselves.  Think of these services as part a public infrastructure.

**Comment by Ainali** [comment]
> I am thinking about the idea of a "Digital Public infrastructure" (see https://knightcolumbia.org/content/the-case-for-digital-public-infrastructure by Ethan Zuckerman) where communication tools such as social networking, chat software etc are run not by big tech but by the communities themselves. Think of these services as part a public infrastructure.

I am sorry for not asking my question clear enough, let me try to rephrase it. When you say they are run by "the communities themselves" who are you referring to? Do you mean that, for example, the government of Sweden would run this for Swedish citizens? Or perhaps that the state of California would run one for all of its residents? And are you talking about a possible scenario in the future, or are there any governments already creating policies to implement this as a service for their constituents?

Or do you mean that the people themselves should run this and not have it provided for them by their local government?

**Comment by sharifX** [comment]
Hi @Ainali, Sorry for the confusion. 

I am envisioning this as a public service run by government similar to public tv/radio model. But it could also be a non-profit organisation like wikimedia foundation. I am not aware of any government currently doing this but you are probably aware of initiatives like Public Spaces (https://publicspaces.net/english-section/). I think codebase stewardship might be an interesting addition there.

**Comment by Ainali** [comment]
Thanks for the clarification, now I understand what you mean!

**Comment by Ainali** [comment]
Feedback has been integrated into this new list in publiccodenet/blog#278
