### ISSUE TITLE
Review for referrals to roles

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1036]
In some places we refer to roles like "operations coordinator". Review the entire about for such referrals and update them if they are outdated. Some specific roles to look out for:

- operations coordinator
- membership developer

**Comment by clausmullie** [comment]
There are 38 instances of 'operations coordinator' and 0 instances of 'membership developer' on the About repository.

I would refrain from changing the operations coordinator role for now, as this involves organisational wide restructuring and is linked to out open vacancy for an [administrative employee](https://github.com/publiccodenet/publiccode.net/blob/develop/careers/administrative-employee.md).

**Comment by clausmullie** [comment]
As for name mentions, there are now 0 instances of 'Deborah' or 'Laura', except for time-specific pages, like financial updates, which can remain as they are.

**Comment by Ainali** [comment]
Yeah, this one is not as easy as just removing it or changing to another role. It rather will need some discussion on where some tasks will land from now on.
