### ISSUE TITLE
Restructure Codebase stewardship

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1076]
@ericherman, @clausmullie and I had a meeting today and were thinking about how we can make Codebase stewardship clearer. We noticed that the "tree" it builds is not really helpful and makes it harder to discover some activities. Just the URL "/activities/codebase-stewardship/activities.md"  is a warning sign.

We decided that we want to try to move everything on that page up one level to "/activities/codebase-stewardship/index.md" and make one canonical page for stewardship. After we have done that, we can look to deduplicate text and links. When reviewing, we need to be careful to not miss adding appropriate redirects.

We also felt that we should make sure that all activities becomes listed on the activities index.

As our thinking around stewardship has evolved, we also want to review if the division in the four categories community, quality, support and product really are useful in the way it is listed now. We have realized they are more facets of the work, that every steward is doing at different times. It also feels a bit like all of them are different perspectives on community which further signals that the divide is not helpful.

**Comment by clausmullie** [comment]
Good to keep this issue open as reviewing the division of the four categories is still pending.
