### ISSUE TITLE
Do we want a URL shortener?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1087]
For our communications, and perhaps social media and the podcast in particular, it might be nice with short and catchy URLs for assets that we are particularly keen to spread. For instance, our beautiful Case for support PDF lives on https://files.publiccode.net/nextcloud/index.php/s/Cb2BN2mn9jzggRz and to sign up to our newsletter and community call one goes to https://odoo.publiccode.net/survey/start/594b9243-c7e5-4bc1-8714-35137c971842

A downside with URL shortening is that the real target is obscured, it is less transparent to the audience. Although, one could question how much value the transparency the example URLs really gives to a human.

It is of course also one extra tool to maintain. Still, I believe the gains might be worth the costs.

**Comment by bvhme** [comment]
I would rather have clear names and URLs than a URL shortener. It's easier for me to remember hypothetical `publiccode.net/team/jan-ainali` or `files.publiccode.net/case-for-support` or `about.publiccode.net/organizations/articles-of-association` than URL shortener URLs.

We can use the redirects that the Jekyll Theme provides for redirecting anything from the publiccode.net site, although perhaps it won't work as well for files, I haven't tested.

**Comment by Ainali** [comment]
Yes, I agree that when possible, a legible URL should be chosen. Neither of my examples are located on the publiccode.net site, would they still be redirectable from it? 

To be clear, I don't suggest that we should create short URLs for every page on all our sites, but rather have the possibility to do so *when their natural URLs is **not** easy to remember*.

**Comment by Ainali** [comment]
> Do we have some specific examples where it would be useful?

My examples in the issue are not hypothetical, they are real. In our podcast now, the simplest I have come up with is "you find the link in the footer of our website at publiccode.net" rather than to just say "you can sign up at `shorturl`/signup"

**Comment by Ainali** [comment]
I realized that my last comment adds another constraint, and that is not only that it should be fairly short, it should also be easy to say and hard to mistake for something else.

**Comment by Ainali** [comment]
Just a note that [Yourls](https://yourls.org/) can do custom URLs.

**Comment by ericherman** [comment]
This looks fine: seemingly not too hard to set up and maintain.
