### ISSUE TITLE
Current priorities on mission page

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1101]
On the page [Mission, founding principles and current priorities](https://about.publiccode.net/organization/mission.html) there is a section with the heading "Current priorities". However, it has not been kept up-to-date. The question is, do we want to keep a section like this that we continuously are updating or is that better suited somewhere else (perhaps as issues on a project board in GitHub)?

**Comment by ericherman** [comment]
A "mission" page shouldn't have something which changes quarterly, thus I'd say priorities at the Policy Plan level could make sense, but then we could link to that.
