### ISSUE TITLE
Sign up sheet for mailing list can't be filled in

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1106]
Our [sign up sheet](https://odoo.publiccode.net/survey/594b9243-c7e5-4bc1-8714-35137c971842/a7f2fb78-3cc1-4d1d-89c9-bbd7c1cabbbb) for the mailing list doesn't seem to allow users to fill in information. 

This was reported as a bug by a user via email. I get the same bug on both firefox and brave. May have something to do with the recent update in Odoo.

**Comment by Ainali** [comment]
Looking in the detailed answers (Participations > Participations), it looks like the last properly recorded was December 8. And then from January 27 there are only incomplete answers but still logged as rows. And a lot of them.

**Comment by clausmullie** [comment]
It seems all the question settings were reset at some point, most likely during the last update - all the surveys had blank unfillable questions. 

I have reset the mailing list survey and done a test submission. It looks like all previous answers to the surveys have been wiped as well. They are all already on the list/invitations, but this may mean we have lost the paper trailing for their consent.
I also reset the openzaak early release survey, as I thought that might still be in use.
The other survey's didn't look active.

@Ainali Do you know if the other three surveys are still being used? If not, can I remove them?

**Comment by Ainali** [comment]
I think the Releae Early Notice is still used, and it also have these blank answers, starting on January 29.

**Comment by ElenaFdR** [comment]
> It looks like all previous answers to the surveys have been wiped as well. They are all already on the list/invitations, but this may mean we have lost the paper trail for their consent to be added.

This is an interesting problem to mitigate. We could download spreadsheets to have snapshots, but then we're back at the problem of people's personal data being stored in multiple places.

**Comment by clausmullie** [comment]
Update:
- Surveys no longer in use have been cleaned up
- Questions on newsletter and openzaak early release surveys have been reviewed and are correct
- No data was lost, as people who signed up are on the mailing list (separate from the survey), we can remove these easily should we get a request from them to do so
- The survey dashboard has changed somewhat - it seems it's no longer possible to export the results as a csv - meaning new sign ons will have to be added manually one by one. A nuisance, but not an issue worth tackling with the current sign on rate.

Final action before closing the issue:
- [ ] The [instructions for managing the newsletter](https://github.com/publiccodenet/about/blob/develop/activities/communication/sign-up.md) should be updated
