### ISSUE TITLE
Our mission is somewhat ambiguous

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1110]
I believe that our [mission](https://about.publiccode.net/organization/mission.html) is ambiguous. Do we:

1.  enable public-purpose (software and policy) that is open and collaborative, or
2.  enable (public-purpose software) and (policy that is open and collaborative)

While I think we want to say 1. the way we have written it makes it sound like 2. Especially when reading it out loud, it's easy a small pause because of the "and" naturally gets inserted.

A simple solution could be: 

> To enable public-purpose software and policy – that is open and collaborative.

Other solutions might be to change the order of the words more fundamentally.

**Comment by ericherman** [comment]
Indeed. While not catchy, a longer sentence would likely be more clear.

**Comment by Ainali** [comment]
Of these I like `c)` the most because it is more clear that it is not only working-in-the-open, which one could do with a closed-source codebase, but also more clearly go towards the [open definition](https://opendefinition.org/).

**Comment by ericherman** [comment]
I like the spirit of `c)`, minor grammar nit: I think "become" should be "to become"
