### ISSUE TITLE
Reduce complexity of documentation on codebase auditing

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1111]
The codebase auditing activity currently contains four pages; the index, two resource pages on the process and certification, and a template. 

This could be refactored to just one page a template, as the index and both resource pages are just a paragraph long. This would reduce complexity and make it easier to understand the information. This also still gives plenty of flexibility for the subheadings to grow.  We could consider breaking it up again if/once it becomes too much to have on one page.

Steps to take:
- [ ] Integrate content from two resources pages into index, taking care of hyperlinks
- [ ] Set redirects from index
- [ ] Delete both resource pages

**Comment by Ainali** [comment]
I imagine that the certification page will grow a lot as soon as we get our first codebase to a state that it would be certified. Not only will the process be documented in greater detail, we will also need to document the technical system that verifies a codebase version as certified as well somewhere.

**Comment by clausmullie** [comment]
Good points Jan - and seeing as About is now a staff manual, we can keep it as it is and slowly increase the content
