### ISSUE TITLE
Consider creating a personalised 404 page

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1120]
Working on #1115 surfaced the idea that we could improve [our 404 page](https://about.publiccode.net/cupcake).

It is now very generic. Could we include a more user friendly note? Something with our logo, a note asking people to check the link, provide a search bar, and inviting them to reach out to us (issue/email?) if they can't find what they are looking for?

**Comment by Ainali** [comment]
Here is the documentation on how it is done: https://jekyllrb.com/tutorials/custom-404-page/

I am uncertain if we can just put a page in [publiccodenet/jekyll-theme](https://github.com/publiccodenet/jekyll-theme) but we should investigate that If not, create a template file to manually add to all our repos.

**Comment by clausmullie** [comment]
It looks like we have a [custom 404 page](https://github.com/publiccodenet/jekyll-theme/blob/master/404.html) in the jekyll-theme repo

**Comment by Ainali** [comment]
> It looks like we have a [custom 404 page](https://github.com/publiccodenet/jekyll-theme/blob/master/404.html) in the jekyll-theme repo

Then that answers my uncertainty because when I build our sites locally no 404 page is generated. We then need to copy it manually to all our repos.

Do we want to improve it a bit before copying it?

**Comment by clausmullie** [comment]
How about we get it working first, and then iterate on the content?

I expect it to render with the footer and navigation from the jeykll theme (`layout: default`) - so I'm curious as to how that will look, and whether that will also affect what we think should be on the page.
