### ISSUE TITLE
Reconsider how our contributing files interlink

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1126]
Surfaced while working on #1116.

We could consider a repo wide review of our contributing files. This could include:
a) Deciding whether we want to have one 'main' file on about, which all other contributing files link to. The about one could be 'contributing to the Foundation' with git instructions and so forth, while the others could have a call out inviting to read the about one, and then continue on with their repo specific instructions. This would deduplicate content, reduce maintenance, and maximise the investments we make to improve the one on about (I think I've seen this done in other organizaitons). 
b) Both the standard and jekyll theme repo's have quite nice (identical) [contributing.md files](https://github.com/publiccodenet/standard/blob/develop/CONTRIBUTING.md). We could scan these for things can be reused to improve the one on about
c) scan for other repo's that don't have a contributing.md file (eg projects.publiccode.net)

My sense is this is a not urgent, but good to set an example for what we encourage others to do

**Comment by Ainali** [comment]
Of these, I think that c) have some urgency to it.

**Comment by clausmullie** [comment]
Could also source ideas from the [GitHub contributing guide](https://github.com/github/docs/blob/main/CONTRIBUTING.md)
