### ISSUE TITLE
Consider investments in improving documentation around the OpenZaak market consultation.

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1136]
Improvements can be made on the documentation around the OpenZaak market consultation.

## Easy enhancements

Improve how existing assets interlink. 
There are currently assets on https, the blog, the podcast, about and the openzaak market consultation repo. These do not all interlink.

- [ ] #1137
- [ ] market-consultation repo: add links to blog and podcast
- [x] podcast: add links to all
- [ ] about: add links to all(?) (currently only blog)

## Possible mid-size enhancements 

- [ ] market consultation repo: review the text from the perspective of a new and uninitiated reader and improve how well it explains what the content, goal and outcome was of this work

## Questions to consider when deciding on prioritising and investing in new features

* does the market consultation remain a one-off, and investment can go into building a strong case study archive in the openzaak/market-consultation repo?
* is it likely vendor ecosystem set-up work will be repeated, and if so, should investing in extracting reusable process and learnings into About be prioritised? (incl how to use the [workshops](https://github.com/publiccodenet/about/blob/develop/activities/workshops/index.md) for this)
* is there enough interest to warrant follow up work to evaluate what the consultation enabled, potentially leading to a business case?

## Existing unpublished work that can be built on

* [old coordination board with actions to take (not fully executed)](https://miro.com/app/board/o9J_kraRkog=/)
* [**private** google doc with note dump](https://docs.google.com/document/d/1VleizeveUvj4m_E9tCPu6_INsPZYd2JKhC_3Q2VHz5c/edit?usp=sharing)
* [notes on what openzaak can do for vendors, and vendors for openzaak](https://hackmd.io/YnVIl-9cTa2D0gfO_0-XcA)

**Comment by ElenaFdR** [comment]
While this is still interesting to people who haven't considered group public sector FOSS procurement before, we will not be doing this before staff leave on 1 April 2024.
