### ISSUE TITLE
Where do we store team rituals?

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#114]
Do we create a `/processes` folder?

**Comment by ElenaFdR** [comment]
Alternative proposal: /howwework, to make clear that it's not a process someone else engages in with us (it's not a weird translation of products or services).

**Comment by bvhme** [comment]
Perhaps we can put this into a contributor guide aimed specifically at people who are employed, have an @publiccode.net email address or who have a key to the office.

**Comment by ElenaFdR** [comment]
Fixed in #359.
