### ISSUE TITLE
Bug in how membership pages interlink

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1149]
The [member relations](https://about.publiccode.net/activities/member-relations/) page includes a subheading on member growth, but is not linked to the [member growth index](https://about.publiccode.net/activities/membership-growth/).

These should at least be interlinked, or otherwise brought in clear relation to each other. (Or even merged, but there was probably a good reason to separate them in the first place, which I can't recall/am not aware of)

**Comment by Ainali** [comment]
They also seem to be aimed at potential members rather than us. That part should preferably be on publiccode.net and the pages on about should be aimed at staff on how we support potential members becoming members.
