### ISSUE TITLE
Lifecycle link missing

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1150]
In commit 3fce62e12659cce6283f5fc21a6aed05786b00d6 I missed that we from [this page](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/lifecycle.md) redirect to a section that we removed. I also missed that we removed the only link to the [lifecycle diagram](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/lifecycle-diagram.md).

I noticed the redirect since both [For existing projects](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/for-existing-projects.md) and [Tracking codebases in Odoo](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/odoo-codebases.md) have links that get redirected.

**Comment by Ainali** [comment]
Suggestion: 
1. We add the text that was removed in that commit to the [lifecycle diagram](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/lifecycle-diagram.md)
2. We change the redirect to the [lifecycle diagram](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/lifecycle-diagram.md)
3. We fix the links in [For existing projects](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/for-existing-projects.md) and [Tracking codebases in Odoo](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/odoo-codebases.md) to point directly to the correct page without a redirect
4. We add a link to the lifecycle page in the top of the further reading of our [product development activity](https://about.publiccode.net/activities/product-development/)

Does that seem like an appropriate solution?

**Comment by ericherman** [comment]
https://github.com/publiccodenet/about/runs/6911562675?check_suite_focus=true#step:5:21
