### ISSUE TITLE
Automate review template updates

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1201]
Every time we make a release of the Standard for Public Code, we update [the review template](https://about.publiccode.net/activities/codebase-auditing/review-template.html) manually. This is mostly a copy and paste exercise but it is easy to make an error. Could this perhaps be automated in some way?

**Comment by SantosSi** [comment]
Do we have a standard for writing criteria documents? I could not find one.
What I spotted from .md criteria files, the content for the review-template is between "## Requirements" and the next "##" at the beginning of the line.
An initial command for the above would be: awk 'BEGIN {p=0}; /## Requirements/ {p=1 ; next};  /##/ {p=0 ; next}; p {print}' <filename>
Also, I suppose the items are one-liners after "*" at the beginning of the line. This would be to analyse the output of the command before to get the Requirements section content.
Once these rules are confirmed, scripts are easier to write.

**Comment by ericherman** [comment]
See also: https://github.com/publiccodenet/standard/issues/634

**Comment by Ainali** [comment]
With the release yesterday, all requirements are now indeed one-liners.

**Comment by ericherman** [comment]
We now generate the [review-template](https://github.com/publiccodenet/standard/blob/develop/docs/review-template.md) from a [script](https://github.com/publiccodenet/standard/blob/develop/script/generate-review-template.sh).

We should update the About repository after the next release to replace the review template with pointers to publiccode.net and the repository main branch.
