### ISSUE TITLE
Rewrite some of the texts of our website

### ISSUE THREAD

**Issue by brandmuse** [publiccodenet/about#1226]
Our website is not currently SEO friendly.  Here is the copy from our Home Page:

We help public organizations collectively develop and maintain **public code.** (assuming everyone on the website already knows what Public Code is. It also sounds like a resume of someone. **We need to be intentional about who we are speaking to here.** I assume we are speaking to public organizations here. In our Storytelling document, we identify a few personas in this space, it is recommended we write as though we are speaking to them. More effective web copy uses the second person pronoun YOU.)

This results in higher quality services for the public that are more cost effective, with less risk and more local control. (These are clear benefits of working with Public Code. **We need to convert these benefits to benefits of the benefits. By answering the question WHY, we can dig further into what cost effectiveness means, or local control.** )

We define ‘public code’ as open source software developed by public organizations, together with the policy and guidance needed for reuse. ( Still some jargons here. **Need some tweaking** Otherwise, this statement can be more effective when it follows the rewriting mentioned above.)

Only have a minute? [Get to know us through this leaflet](https://files.publiccode.net/nextcloud/index.php/s/Cb2BN2mn9jzggRz#pdfviewer) 
**This external link should be after the fact. Could we bring this to the website? Perhaps use this as the basis for the rewriting mentioned earlier. Graphics have to be consistent and more intentional stylewise. It is also an opportunity to invite people to join our community**

Generally, our key phrases or keywords, other than Public Code, are clearly missing here. We need to give teh search engine something to to take away by answering the questions

**1. How
2. Why
3. What
4. Where are these used
5. Which tools etc** 

[Contribute to our community](https://about.publiccode.net/CONTRIBUTING.html)

**Comment by ericherman** [comment]
An entire revamp is in progress.
