### ISSUE TITLE
Add German report to value and impact

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#1227]
The report from des Kompetenzzentrums Öffentliche IT mentions us on page 37 and in the sources, and Laura and Claus gets thanked in the intro.
https://www.oeffentliche-it.de/publikationen?doc=255694

Not entirely sure if it fits better on [policy documents](https://about.publiccode.net/activities/value-and-impact/policy-documents.html) or [press mentions](https://about.publiccode.net/activities/value-and-impact/all-press.html), but I lean towards the first.

**Comment by ElenaFdR** [comment]
This looks like a mention by a (state-suppported) think tank. Up until now, the list on 'policy documents' is only government institutions, while all other mentions (including on OSOR and OFE) sit on the press page. I lean strongly towards keeping a list of gov't impact separately from a list of other impact. If 'press' sounds too narrow, let's change the heading on that page? The subheading currently says "Here’s the complete list of all mentions of the Foundation for Public Code on third party platforms" which is very comprehensive  (though almost certainly inaccurate).

**Comment by Ainali** [comment]
Ok, I'll move it to the press page!
