### ISSUE TITLE
Publish communications plan on About

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#131]
> Comms plan lite: how can people can keep up with our news? Define use of channels so we can tell people where to look on Thurs.
> 
> + Twitter
> + FB page
> + mailing list for people to sign up to?
> + blog?
> + Planable
> 
> 19 April 2019: [Unfinished draft here](https://docs.google.com/document/d/1vG6L2xHrGbTqLEwNOrRHFeub3geFd-k_1qzHJY4eJ6o/edit?usp=sharing)
> 
> Agree what we communicate about, how often, and who does it.
> 
> @nebster @elenafdr @bvhme

**Comment by ElenaFdR** [comment]
Reframe as guide for new starters.

**Comment by ElenaFdR** [comment]
15 May: [New draft here](https://docs.google.com/document/d/1Z8CEcLLPgw7Twpcgfa-VGaiPYOzfYSoRNBxaROHI-9w/edit#)

**Comment by bvhme** [comment]
@ElenaFdR I'm curious but don't have access to that link :) 🔐

**Comment by ElenaFdR** [comment]
Note: this is closer to a resource than a guide.

**Comment by clausmullie** [comment]
@ElenaFdR how close are we to closing this? or should we close this issue for now if it is deprioritised?

**Comment by ElenaFdR** [comment]
#539 closes this issue.
