### ISSUE TITLE
Create core pitch deck for Foundation with removable slides

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#133]
Include a bit in the 'for staff' contributor guides

For card:

> To serve a superset of target audiences @nebster @elenaFdR @clausmullie

**Comment by ElenaFdR** [comment]
Still to do: add (removable) membership pitch slides

**Comment by ElenaFdR** [comment]
It looks like @neb added founding membership and additional call to action slides as part of his Code for America prep. I've just made some minor formatting changes (standardized the shade of gray, added our snazzy triangle bullets).

**Comment by ElenaFdR** [comment]
It looks like @neb added founding membership and additional call to action slides as part of his Code for America prep. I've added some of @bvhme's Digi5 slide content, and made some minor formatting changes (standardized the shade of gray, added our snazzy triangle bullets).
