### ISSUE TITLE
Make handbook for staff on tools  (a contribution guide)

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#135]
Boris + Mirjam will work on this

> Include (gsuite - calendar, message, mail -, odoo, Splitwise, Github) here: https://github.com/publiccodenet/about

**Comment by ElenaFdR** [comment]
[draft howwework index text.txt](https://github.com/publiccodenet/about/files/3108481/draft.howwework.index.text.txt)
Here's draft text from the now deleted 'how we work' index page.

**Comment by ElenaFdR** [comment]
Fixed by #359.
