### ISSUE TITLE
Rework Contributing.md 

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1356]
This is currently a very high profile page, linked to from our homepage (`join us`). As About becomes more of a staff manual, this should be reconsidered.

**Comment by Ainali** [comment]
Agreed. It feels natural that the CONTRIBUTING on About turns into a more of how to contribute to that site, and that we should either point the join us-link to partnerships directly or have an intermediate page on publiccode.net with links to partnerships, affiliates and perhaps some other ways of "joining".

**Comment by clausmullie** [comment]
Yes, content should probably be (or link to) https://about.publiccode.net/activities/documentation/

And indeed, have a separate page on .net

**Comment by clausmullie** [comment]
Linked to #1126
