### ISSUE TITLE
Improve resilience of linking

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#1379]
A search tells me About currently has 65 absolute links to https://about.publiccode.net

These should probably be changed to relative links for link resilience

**Comment by clausmullie** [comment]
Some questions here:

For the annual report and policy plan -> the intention is to turn this into a pdf and distribute it -> is this a reason to keep absolute links over relative links? No right? 

For redirects -> is there is a reason to have absolute links? No right?

**Comment by ElenaFdR** [comment]
Obviously you need an absolute link for any link to another website, including other publiccode.net subdomains. Redirects within the same domain (redirects from) should be relative. Our guidance says to use [redirect to](https://about.publiccode.net/activities/documentation/move-merge-delete-pages.html) when a page is moved to another repo, so those would be absolute.

Re docs that should become PDFS, it depends on how the PDF is made. If you're copying the raw markdown into Figma, then a full link avoids more work and potential for error. If you're saving the frontend HTML to PDF, then our print style sheet takes care of it (the formatting is like the Standard).
