### ISSUE TITLE
Describe the organisational structure

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#153]
## Codebase steward

the codebase steward provides the development and community of a codebase with leadership and assistance on quality, community, support and marketing.

## Lead
Prefix 'Lead': The lead acts as the leader in their domain within the team as well as working to grow and develop the team's abilities and act as the domains public advocate.

## Coordinator

the coordinator of a domain makes sure that its role in the organization is fulfilled, they do this by coordinating the activities of team members in their domain, supporting them in their work or fulfilling the role by themselves.

## Chief

the chief is a manager with signing power granted by the board of directors and thus responsible for their area of operations

## Chief executive

Prefix 'Chief': the chief executive is the highest manager in the organization.

**Comment by ElenaFdR** [comment]
duplicate of #310

**Comment by clausmullie** [comment]
@bvhme can we close this? We now have the staff described [here](https://about.publiccode.net/organization/staff.html)

**Comment by bvhme** [comment]
Yes we can, at least the structure is there!
