### ISSUE TITLE
Define lifecycle for codebase stewardship from graph (e.g. assessment, incubation, mature, attic)

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#154]
![codebase-lifecycle](https://user-images.githubusercontent.com/1917629/56947753-647b9880-6b2e-11e9-84bd-78922bab1fc2.png)

**Comment by ElenaFdR** [comment]
@ericherman This may be relevant to #341.

**Comment by ElenaFdR** [comment]
Fixed by #215
