### ISSUE TITLE
Develop strategy on where we can find our quality and community stewards

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#157]

**Comment by ElenaFdR** [comment]
This is done, but not documented.

Off the top of my head, I think we advertise on:
- LinkedIn
- Github
- StackoverJobs
- T9t.io/organizations

@MirjamvT Anywhere else?

**Comment by bvhme** [comment]
Is this not refected in the '[hiring process](https://github.com/publiccodenet/about/blob/develop/activities/recruitment/hiring-process.md)'?
