### ISSUE TITLE
Develop milestone planning

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#159]
---
type: Resource
---

# Milestones

We use Milestones to plan our work around and set priorities. Milestones replace what other organisations would call 'projects' by focussing on the key achievements over certain deliverables.

Milestones have an owner and can have a due date.

Upcoming milestones:

* Standard v0.2.0 2019-05-13 @bvhme
* Choose name 2019-05-30 @bvhme
* Hire codebase steward for community @bvhme
* Hire codebase steward for quality @bvhme
* Found association 2019-05-30 @bvhme
* First intention agreement @nebster
* First member @nebster
* First codebase in Asssesment @clausmullie
* First codebase in Incubation @clausmullie
* Standard v1.0.0 @clausmullie
* First codebase in Mature / Product @clausmullie
* First third party contributor on a codebase @clausmullie
* First third party maintainer on a codebase @clausmullie
* First member contribution @nebster
* First non-director gift @nebster
* Standard v2.0.0 @clausmullie

## How to use milestones

Milestones can be used in GitHub, they can be added to issues as well as pull requests which makes it easier to find and version things.

In our office we have a wall with the milestones on it.

## How to add a milestone

1. Add a milestone to the GitHub repository where possible
    * Mention the owner in the description
    * Set the due date if available
2. Add the milestone to the list above
    * Add an owner
    * Add a due date if available
    * Link to the repository milestone
3. Update the milestone wall in the office

**Comment by clausmullie** [comment]
should be inline with #213

**Comment by MirjamvT** [comment]
How do we visualize/write the milestones achieved? 
Some are 'done' (of which some have a date in the past, and some don't
Some have a date in the past, does that mean they are 'done'?

**Comment by ElenaFdR** [comment]
[The content that we put up on develop]( https://github.com/publiccodenet/about/blob/develop/organization/milestones.md) isn't exactly the same as @bvhme's suggestion above - it only includes future milestones.
I propose we create a 'past milestones' page with a list of achieved milestones, ideally with each one of them hyperlinked to whereever we've announced it publicly (our blog or Twitter). [Our comms plan](https://docs.google.com/document/d/1Z8CEcLLPgw7Twpcgfa-VGaiPYOzfYSoRNBxaROHI-9w/edit?ts=5cdec642#heading=h.sgjl8fdb0vwy) calls for celebrating each milestone with a campaign.

**Comment by bvhme** [comment]
Those seem like great new issues :)

**Comment by ElenaFdR** [comment]
#259
