### ISSUE TITLE
Suggested texts to describe job description (QSfQ, QSfC) on social media (FB, Twitter, LinkedIn)

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#160]

**Comment by bvhme** [comment]
This was closed in #178

**Comment by ElenaFdR** [comment]
This ticket was specifically to develop taglines for Twitter and other social media.

Suggested Twitter texts:

Open source community managers! Come grow strong open source communities around public-purpose codebases as the Foundation for Public Code's new codebase steward for community: <https://about.publiccode.net/roles/community.html>

Developers! Come help producers of public purpose, open source software improve quality and reusability by testing against the Standard for Public Code - become the Foundation for Public Code's new codebase steward for quality: <https://about.publiccode.net/roles/quality.html>

**Comment by ElenaFdR** [comment]
@MirjamvT suggested these tags: #JobOpening #Jobs #wearehiring  #opensource RT=heart

**Comment by bvhme** [comment]
Ahh sorry, my very bad

**Comment by MirjamvT** [comment]
and i did mean an emoji, not the word 'heart'.

**Comment by ElenaFdR** [comment]
LinkedIn variation:
We're hiring! Come help us create thriving open source communities around high quality, reusable software built by and for public organizations worldwide.  (shared above: https://about.publiccode.net/roles/)

**Comment by MirjamvT** [comment]
Love it
