### ISSUE TITLE
Align About to refer to only 'activities' and not 'services'

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#165]
This is to propagate the decision that referring to 'services' can cause confusion as services are typically paid for directly, while we want to provide more ecosystem-level support

**Comment by bvhme** [comment]
So, remove mentions of 'service' from the following files:

* `index.md`
* `activities/index.md`
* `activities/documentation/about-folder-structure.md`
* `activities/codebase-stewardship/index.md`
