### ISSUE TITLE
The brand needs to have a resource in the about

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#166]
Pointing mostly towards the <brand.publiccode.net> resource

**Comment by clausmullie** [comment]
@bvhme can you clarify the problem?

I see that in about/index.md we have a line
``` Additionally we have separate sites that show our projects and how to use the brand. ```
with [how to use the brand] linking to https://brand.publiccode.net/

Perhaps this was added in after this issue was created?

**Comment by bvhme** [comment]
It was, and should be resolved because of that, however a mention somewhere in communications or something would also not be misplaced.
