### ISSUE TITLE
Formulate descriptions of our communities, audience, users and contributors

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#21]
For this I'm just wondering a bit on whether we should be doing this in this repository. Perhaps in a `communications` folder or something.

[Mozilla Open Leaders assignment](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/)

**Comment by bvhme** [comment]
This issue could probably be the same as #32

**Comment by ElenaFdR** [comment]
This need has been met elsewhere.
