### ISSUE TITLE
Add business process modelling notation to glossary 

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#216]

**Comment by bvhme** [comment]
I'd say this is not part of our glossary, we can add some guides for it to the `activities/documenting` section but I don't think this is a term specific to what we're doing, as it is an open standard.

**Comment by clausmullie** [comment]
Close this issue until we have need to explain BPMN in our `activities/documenting` section

**Comment by bvhme** [comment]
Also, BPMN is not a term we need to control, better to point outwards.
