### ISSUE TITLE
the road map does not have (time) ordering of activities

### ISSUE THREAD

**Issue by MirjamvT** [publiccodenet/about#220]
activities in the roadmap currently in 'random' order, per phase. the notion of a roadmap seems to suggest that writing up items in time order is logical.

see #213

**Comment by bvhme** [comment]
The list of activities does not list activities that follow up on each other or that have a requirement on each other, they all need to be done at the same time. I don't think it is possible to put them in a time order.

**Comment by ElenaFdR** [comment]
Tagging issues to milestones would help with legibility and prioritization. (This would build on #159).

**Comment by ElenaFdR** [comment]
Closing with 'wontfix' since this can't be fixed for the items currently on our roadmap.
