### ISSUE TITLE
 How to differentiate between code bases in our stewardship and other software that could be public code

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#223]
# Context

We are building a trust machine for stewarded code bases developed and maintained to a specific standard. We need to be able to refer to this. However, a) others in the ecosystem are already using public code, b) others may apply our standard without being audited by us (yet), c) others may create their own definition of public code and standard(s) for this.

# Issue

Some of our team currently use ‘**P**ublic **C**ode’ to refer to code bases stewarded by us. However, this is not very ‘secure’ or ‘scalable’. One idea could be to build a brand around ‘Foundation Stewardship’ with a mark + status (Incubation, Mature, Attic etc) so that this can serve as the differentiator trust qualifier. We could then refer to ‘code bases Stewarded by the Foundation for Public Code’

Other open source govtech software can then be ‘public code’, as part of our mission is to raise awareness about this and have others join our mission.  

# Next steps
- [ ] Organize a team sprint to work on this issue further
- [ ] Make a pull request to the ‘Activities’ section

Issue made with @nebster and @ElenaFdR

**Comment by bvhme** [comment]
I agree with this, it is crucial that _Public Code_ remains and grows as a community term.

The way this is done by other _foundations_ is that they call a mature stewarded codebase a _project_ specifically. I personally feel that does not communicate well and there are some problems with _project_ versus _product_.

The advantage of that is to say that we only connect our brand to codebases that actually are mature, and so our brand becomes the mark of trust, which I feel is exactly what we want. When people see our mark they should know they are safe.

**Comment by ElenaFdR** [comment]
@ericherman, do you have any views on this?

**Comment by bvhme** [comment]
@clausmullie, is there something we can do to move forward on this or shall we close the issue?
