### ISSUE TITLE
Our Stewardship Index is mix between marketing and about

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#226]
## Context
While linking to new files the code base stewardship I noticed it was a mix between an About index and marketing. I think this page was built before we defined out About structure. 

## Problem/idea
I would expect an About page to give me an overview of all the resources and guides we have on a certain activity, along with a bit of context. This page feels more targeted at members, is more marketing like, and replicates text from the marketing page

## Proposed actions
- [ ] Move any good marketing content onto marketing page
- [ ] Rewrite index to make it more functional/operational dashboard 
- [ ] Link to marketing page at top of Index
- [ ] Fix 'code base' to 'codebase' in full folder to align to our style guide (for extra points! :tada:)

**Comment by bvhme** [comment]
'Code base' is a thing? That is new to me. You speak of this mythical style guide, where could I find it?

I have to say that it makes little sense to me with space in between and I've never seen it before, but it can be done grammatically I guess.

**Comment by clausmullie** [comment]
O, yea I have been using 'codebase' as well and this makes sense to me too. But I caught something diagonally about it needing to be separate.. but I may have heard wrong. 

@ElenaFdR what's your opinion on this?

**Comment by ElenaFdR** [comment]
'Codebase' appears to be in far more common usage than 'code base'. I've used 'codebase' throughout. Neither version is currently in our mythical style guide.

**Comment by clausmullie** [comment]
Nice, let's get rid of 'code base' then!

**Comment by ElenaFdR** [comment]
This is obsolete content.

**Comment by clausmullie** [comment]
Closing this issue as we now have a restructured [index](https://about.publiccode.net/activities/codebase-stewardship/) live. :tada:
