### ISSUE TITLE
We should update our new mission across the website

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#227]
Several places still have:
> Our mission is to create a viable future for public organizations and civic operating systems that are highly participatory and drive societal engagement.

While our new mission is:
> To enable public-purpose software and policy that is open and collaborative.

**Comment by bvhme** [comment]
Once we close #217 :)

**Comment by bvhme** [comment]
Perhaps as part of #217

**Comment by clausmullie** [comment]
#217 closed ;) 

so let's keep this one active

**Comment by ElenaFdR** [comment]
Also checked http, Standard, brand, projects and illustration repos.
