### ISSUE TITLE
Metrics: What are our success metrics?

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#230]
## What are our organization's success metrics?

We need success metrics for our organization. This could include things such as: 
* Member growth
* Code bases in stewardship
* Societal impact of our work
* Code base contributors and maintainers
* Financial support from structural funding and philanthropy
* Ecosystem: affiliate organizations which share our mission
* Partners: private sector implementation and maintenance partners for Public Code bases
* Uptake and implementation of our resources beyond our members and contributors (such as the standard)

### Next steps:
- [ ] Sort into impact/outcome/output
- [ ] Define how to measure these

For storing metrics see #219

**Comment by ElenaFdR** [comment]
We've agreed that our current success metric is if [we're meeting our milestones](https://about.publiccode.net/organization/milestones/).
