### ISSUE TITLE
ripping off, seems too loaded a phrase

### ISSUE THREAD

**Issue by MirjamvT** [publiccodenet/about#238]
I'd like to report an issue in `activities/member-relations/user-mapping/political.md`

"companies evolve to rip off government" -> something like: companies may take advantage of extending a contract

**Comment by ElenaFdR** [comment]
I don't see a problem with this language - it seems to clearly describe a perceived incentive problem with the current market.
Are you concerned that someone could be offended by this? Or is the language too casual?

**Comment by MirjamvT** [comment]
We don't need to create a suggestion of being anti-corporate, and I think this choice of words does that. The remark is not explicitly about the incentives involved.

**Comment by bvhme** [comment]
@ElenaFdR, is this still considered relevant to change or shall we close the issue?

**Comment by ElenaFdR** [comment]
I still don't see a problem with this language; I support closing this.
