### ISSUE TITLE
Update the organization's name

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#244]
We may need to update the organisation name and logo everywhere these appear. 
This is:

- [x] logo files
- [x] [Brand repo](https://github.com/publiccodenet/brand)
- [x] [About repo](https://github.com/publiccodenet/about)
- [x] [Blog repo](https://github.com/publiccodenet/blog)
- [x] [Projects repo](https://github.com/publiccodenet/projects)
- [x] [Illustrations repo](https://github.com/publiccodenet/illustrations)
- [x] [Standard repo](https://github.com/publiccodenet/standard)
- [x] [Jekyll theme repo](https://github.com/publiccodenet/jekyll-theme)
- [x] [Smart Cities? Public Code! repo](https://github.com/publiccodenet/smart-cities-public-code)
- [x] [Marketing site](https://github.com/publiccodenet/http)
- [x] [Jekyll theme starter kit](https://github.com/publiccodenet/jekyll-theme-starter-kit)
- [x] [publiccode.yml](https://github.com/publiccodenet/publiccode.yml)
- [x] job templates
- [x] member relations docs templates
- [x] core pitch deck
- [x] demo deck
- [x] email signatures
- [x] office manual

Non-digital artefacts:
- [x] business cards
- [x] the Standard standard

**Comment by ElenaFdR** [comment]
This isn't currently necessary. We'll reopen this if and when it becomes necessary.
We've removed the wontfix label because we'll definitely fix this if it becomes necessary.

**Comment by ElenaFdR** [comment]
This should be done at the same time as #273.

**Comment by ElenaFdR** [comment]
#292 covers About. 
[#16](https://github.com/publiccodenet/jekyll-theme/issues/16) proposes updating the footer on all other repos.

**Comment by bvhme** [comment]
I'm going to close this as I think it is complete
