### ISSUE TITLE
Research 'partner' value proposition and Quintel as potential case study material

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#245]
## Context

Earlier this week we had a great exploratory meeting with @chaelkruip [Quintel Intelligence](https://quintel.com) - who have developed an awesome open source [Energy Transition Model](https://github.com/quintel) which is being used by many public organizations. 

## Idea

It would be great to organize a follow up meeting in which we could explore:
* Developing a case study about the successful relationship between an open source provider and public organizations, and how ‘public code’ could enhance this
* Run our assumptions past them on how our [codebase stewardship](http://publiccode.net/codebase-stewardship/) of public codebases could help improve the ecosystem for their type of vendor (ie by improving the resilience and longevity of public code projects) 
* Learn from how different public organizations procure their open source services as research for our Support stewardship activities
* Explore if some of their partners would be suitable first members for our organization 
* Have Quintel staff feedback on our [standard for public code](http://standard.publiccode.net/) 

## Next step
 
[ ] Define mutual agenda and set a time together with @chaelkruip and @ElenaFdR 
[ ] Define which information products we could develop for About (such as a case study resource, or early iteration of our procurement guide)

**Comment by ChaelKruip** [comment]
> Define mutual agenda and set a time together with @ChaelKruip and @ElenaFdR

I am very much open to do this! Let me know by mail or phone what is convenient and timely for you!

**Comment by bvhme** [comment]
Hey @ChaelKruip, priorities shifted and we've still not gotten to this. I'd still be very interested but we can't go into this right now :(

I'll close this issue for now but hope to reopen it soon.
