### ISSUE TITLE
We link to /roles instead of roles/index.md on the site

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#256]
- [ ] /roles should be ../roles/index.md
- [ ] links to this need to be updated across the site

**Comment by clausmullie** [comment]
@ElenaFdR could you please clarify?

I located the /roles/index.md page so not quite sure what you mean

**Comment by bvhme** [comment]
There is one link that points to `roles/` in the `roadmap`, that should point to the `index.md`
