### ISSUE TITLE
Value proposition can be enhanced with 

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#268]
Our [value proposition mapping](https://about.publiccode.net/activities/member-relations/user-mapping/) currently includes for each user:
* Positive reasons for why they might be interested in our work
* Negative reasons for why they might be interested in our work
* Our main value proposition for them

We could add another section
* Reasons for why they might be hesitant about our work

in order to understand their user story better, anticipate critical feedback, and formulate a good response

**Comment by ElenaFdR** [comment]
Closing because so far no potential members have asked for this; we'll reopen this when someone definitely tells us they would find this useful.
