### ISSUE TITLE
How can we sustainably fund the Foundation so it can be a long term partner

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#27]
Looking for funding and business models. We believe in order for any code in the care of the Foundation to be usable it needs to have a guaranteed stewardship of at least a few years. (but how many)

So far we've been considering 3 major sources of revenue:

* City partners
* Codebase donators through endowments
* Implementation partners
* Grant funding
* Philanthropic funding

How are others doing this, solving this problem, and how can we?

**Comment by ElenaFdR** [comment]
Closing because this question is too meta.
