### ISSUE TITLE
Publish legal info about Foundation (KvK registration number, etc)

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#273]
This includes:
- [x] de officiële naam van de instelling
- [x] het nummer dat aan de instelling is toegekend bij inschrijving in het handelsregister (RSIN)
- [x] het post- of bezoekadres, dan wel het telefoonnummer, dan wel het e-mailadres van de instelling
- [x] de doelstelling volgens de regelgeving van de instelling
- [x]  de hoofdlijnen van het actuele beleidsplan van de instelling
- [ ] de bestuurssamenstelling, het beloningsbeleid en de namen van de bestuurders

The official government list is here: https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/bijzondere_regelingen/goede_doelen/algemeen_nut_beogende_instellingen/gegevens_van_een_anbi_publiceren_op_een_internetsite/gegevens_van_een_anbi_publiceren_op_een_internetsite

De uitzonderingen zijn niet van toepassing.

**Comment by ElenaFdR** [comment]
This should be done at the same time as #244.

**Comment by ElenaFdR** [comment]
I love this approach to adding some human interest to a board page: https://www.knvir.org/knvir/477-2/

**Comment by ElenaFdR** [comment]
Dependencies/missing links:
- [ ] Association bylaws
- [ ] Blog in linkable state
- [ ] Bank number

**Comment by ElenaFdR** [comment]
I've removed the reference to the bank account for now.

**Comment by ElenaFdR** [comment]
These 2 things can't be done until the end of the first financial year (Jan 2021):

- [ ] een actueel verslag van de uitgeoefende activiteiten van de instelling
- [ ] binnen 6 maanden na afloop van het boekjaar: de balans en de staat van baten en lasten, met toelichting. Hierin moet onder meer het totaal aan ontvangen giften en erfenissen w. orden vermeld

They are captured in issue #

**Comment by ElenaFdR** [comment]
@MirjamvT Once all of the PRs mentioned in this issue are closed, please confirm you can find all the info required on our website.

**Comment by bvhme** [comment]
What is the reason we need to wait for the end of the book year to publish 'een actueel verslag van de uitgeoefende activiteiten van de instelling', I'd guess we've already done enough to do this.
