### ISSUE TITLE
Reconsider use of word 'project' when we mean 'codebase' or the Foundation

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#281]
Background:
On #247 @ElenaFdR mentioned @bvhme considers the word 'project' to be paradigmatically wrong for software powering services, which is only over when the service is replaced or decomissioned.

Next step:
Reconsider how we use this word in our vocabulary, and what it should refer to. Including things such as a) the work we do with members, the work members do without/before us, things we do.

**Comment by ElenaFdR** [comment]
Alternative words we use are:
- codebase
- repo

While we might consider 'project' an antipattern, they still form the basic unit of work for much of the rest of the world.

**Comment by bvhme** [comment]
Mentions of the word codebases in this repository can be found here: https://github.com/publiccodenet/about/search?q=project&unscoped_q=project

**Comment by clausmullie** [comment]
Deprioritising this for now
