### ISSUE TITLE
Update that we are 'founded' across our content

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#282]
Items include:
- [x] Membership Information template
- [x] Expression of Interest template
- [x] Membership Proposal template

- [ ] Look for other instances to change 

Indirectly linked to #244 and #273 and  #291

**Comment by clausmullie** [comment]
For each of the three templates I have:
* Made the first mentions "Foundation for Public Code Vereniging", with a footnote explaining we are a verening under dutch law
* For subsequent references removed shorthand to 'Foundation' making it all 'Foundation for Public Code'
* Removed "currently in founding" text to simply state "we are..."
* I have left 'founding member' in, as I feel this is still an appropriate name for them

**Comment by bvhme** [comment]
Yes, very good, can we get the _KVK nummer_ ­— `74996452` — in the footnote as well?

**Comment by clausmullie** [comment]
done

**Comment by ElenaFdR** [comment]
@clausmullie I've left a comment for you on the Founding Membership Proposal.

**Comment by ElenaFdR** [comment]
Communication-channels.md still contains old language, but #291 already includes an update.

**Comment by clausmullie** [comment]
All 3 footnotes updated to:
`We're registered as an association (vereniging met volledige rechtsbevoegdheid) under Dutch law. Our chamber of commerce (KvK) registration number is 74996452.`

**Comment by ElenaFdR** [comment]
Closing because we've finished this.
