### ISSUE TITLE
Broken Link: https://about.publiccode.net/roles/index.md

### ISSUE THREAD

**Issue by jenvandermeer** [publiccodenet/about#293]
I'd like to report an issue in `CONTRIBUTING.md`

**Comment by jenvandermeer** [comment]
Link broken https://about.publiccode.net/roles/index.md

**Comment by clausmullie** [comment]
Thanks @jenvandermeer!

To fix this bug:
1) go to about/contributing.md
2) branch/fork the repository and create a patch which corrects
```We're currently hiring codebase stewards - [see our open roles](../roles/index.md).```
by removing the removing the "../" to make
```We're currently hiring codebase stewards - [see our open roles](roles/index.md).```
3) make a pull request! :tada:
