### ISSUE TITLE
Moving all codebase stewards into the 'hiring section' on the roles index

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#305]
I think we'd benefit from getting rolling applications in all of the codebase steward categories, so I'd be interested in moving the 'Codebase steward for product marketing' back under the Hiring heading.

**Comment by clausmullie** [comment]
@bvhme can we close this? all 4 positions are open under https://publiccode.net/careers/

**Comment by bvhme** [comment]
Yes, good spot!
