### ISSUE TITLE
Improve job candidate user journey with new content

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#310]
Problem: 
- we have content debt because we have CTAs across About saying 'we're hiring codebase stewards!'
- some recruitment resources aren't in the recruitment folder
- we're confused about what the difference is between job descriptions and roles
- we're missing an org chart

Solution:

@clausmullie, @MirjamvT and I have hashed out this user journey:

- [x] On https://publiccode.net/ homepage: have a prominent link to 'careers' (or equivalent label)
- [x] On https://publiccode.net/careers: create a new page with our careers offer/promise (marketing content) plus a list of hyperlinked open roles (including this idea from the old roles index: "[see also our org chart]. We're not hiring for roles not listed on this page, however if you think you fit in to our organization in a way we don't understand yet, please get in touch.") Use this StackOverflow Jobs blurb about the org as source material for the careers page: https://hackmd.io/lannfIybQRSzVznuLRW1sQ
- [x] Each marketing site role link points to a job description located in: https://about.publiccode.net/recruitment/roles
- [x] https://about.publiccode.net/recruitment/roles/index.md has 2 H2s: open jobs and roles we're not recruiting for right now. The difference between a role and and a job is that the job has all of the content of the role description content and a footer with information about that specific job (hours per week, location, how to apply). The index page should explain this difference so that anyone updating a role to a job knows to update the existing role page as well as the index page - include a link to the job description template (https://github.com/publiccodenet/about/blob/develop/activities/recruitment/job-description.md or corresponding live link)
- [x] https://about.publiccode.net/organization/ has an org chart added to it. Each position on the org chart is also hyperlinked to the role description on https://about.publiccode.net/recruitment/roles.
- [x] Add links to https://publiccode.net/careers from anywhere there's a 'join us!' CTA
- [x] Delete https://about.publiccode.net/roles/
- [x] Job descriptions on the `about`

**Comment by ElenaFdR** [comment]
Partial duplicate of #153.

**Comment by bvhme** [comment]
What about us putting the factual information about the organisation and roles on `about` while we put the job descriptions fully on the marketing page. To me, that seems like a cleaner split between the two.

**Comment by ElenaFdR** [comment]
@bvhme Yup, that would be much cleaner. It would also make it clearer when we're recruiting multiple people with the same role but different working conditions at the same time (eg a full time and part time codebase steward).

**Comment by bvhme** [comment]
So for now I've effectively removed the `roles` section from About to be replaced with a `careers` section on the Home page.

This means we have no internal job descriptions (coming in the staff pull request). All information on jobs and joining is on <https://publiccode.net/careers/>.

**Comment by bvhme** [comment]
The staff page is now live, which means the final part of this issue is to create a new `roles` section that can house the descriptions of the jobs.

**Comment by bvhme** [comment]
I think we've made some progress on this and think we should close this issue.
