### ISSUE TITLE
Jan 2021: update website with extra ANBI info

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#311]
Missing info required by our Anbi aanvraag: 
- [ ] een actueel verslag van de uitgeoefende activiteiten van de instelling
- [ ] binnen 6 maanden na afloop van het boekjaar: de balans en de staat van baten en lasten, met toelichting. Hierin moet onder meer het totaal aan ontvangen giften en erfenissen worden vermeld

Deadline: 1 July 2021

Related issue: #273

**Comment by bvhme** [comment]
I'm going to add this to our calendar for the first working day of next year and close it for now. We can reopen it then.

**Comment by bvhme** [comment]
As it is now the next year this is relevant again :)

@Deborah, could you look into what we should be doing?

**Comment by demkodo** [comment]
Hi @bvhme @ElenaFdR @lscheske and I [started preparing this in November](https://docs.google.com/document/d/1LYOhiqf4zMGvNsSTnqgOc1YkfxgfX1TeSJ2NtrIv9ac/edit). It needs to be picked up again. The financial annual statement I pushed our bookkeeper to have that ready sometime in February.

**Comment by ElenaFdR** [comment]
#908 is a duplicate of this.

**Comment by ericherman** [comment]
Both the Annual Report and the Financial Report are available from https://about.publiccode.net/organization/annual-reports/
