### ISSUE TITLE
Agree how to fix nav and build out About taxonomy with least debt

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#319]
(24/6/2019 retro action) 
Surfaced in July 3rd retro as well

**Comment by clausmullie** [comment]
Possible models for about: Onion, Tree, Spaghetti

**Comment by ElenaFdR** [comment]
@clausmullie We're closing this for now because there are no directly actionable items described outside of #310, but feel free to add more context if you'd like this reopened.
