### ISSUE TITLE
How can we evaluate whether a codebase is ready and suitable for stewardship?

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#328]
## Background:

We have developed an initial set of criteria by which to do an initial evaluation of member codebases. This will help Foundation staff to assess which proposed codebases can start the [assessment phase](https://about.publiccode.net/activities/codebase-stewardship/lifecycle.html), and help other members assess which of each other's codebases they might want to reuse.

We have developed [questions for each of the criteria.](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/criteria-for-codebase-stewardship.md) Together, these will be sent as a survey for members to complete for each of the codebases they propose for codebase stewardship. 

This survey is intended to give a general rough sense of codebase reusability.

## Next step:

Get contributors to review the [criteria and question list](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/criteria-for-codebase-stewardship.md) to help us make it:
* more indicative of codebase reusability to all parties
* friendly to fill in by codebase 'owner'
* useful for the potential codebase 'reuser'

**Comment by imingueza** [comment]
In the [question list](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/criteria-for-codebase-stewardship.md), under "Co-develop-ability", in points 11) and 12) (Are there explicit style guidelines for how code should look?):

I would add something like "In affirmative case, could you share the link to the guideline and the automatized checking system that is used?"

It is interesting to see if each one use a different guideline and checking system, or exists a more used common one.

**Comment by imingueza** [comment]
I would add the 2 questions under "Code reusability" section to "Co-develop-ability", because, for me, they are close to questions 11) and 12).

**Comment by bvhme** [comment]
@libremente provided some feedback in the first community call, thanks! :bowing_man: 

* How does the reuse potential section related to codebases that are already reused
* How can feedback from existing reusers be incorporated into the criteria
* As a survey this might be really hard to get this completes, by using it as structured questions in a video call might be the best way to get this input.
* Some simple disqualifying questions that can be used before jumping into this might give an indication for not starting the process
  * Libreoffice has a site where you answer a few questions and sends you to the right place, something like that might be good.
* What is the policy on responding to pull requests and what kind of resources are there to interact with the community, are you able to maintain it.
  * How do we solve the problem that their developers are not there for reviewing pull requests, even if it solves their problems.
* The french are looking for a home for their open source contribution policy, perhaps this would be something the Foundation for Public Code can steward.
* Perhaps the roles that Team Digitale is defining for public adminstration open source people such as 'maintainer' and 'admin' could be reused by the Foundation for Public Code to reduce confusion.

**Comment by clausmullie** [comment]
@zorp has made a pull request with suggestions - see #356

**Comment by ElenaFdR** [comment]
@ericherman believes this ticket is too big to be useful, and will break it down into smaller tickets and then close.

**Comment by ericherman** [comment]
I created an issue in About and two issues in Standard which fell out of this exploration:
* https://github.com/publiccodenet/about/issues/403
* https://github.com/publiccodenet/standard/issues/266
* https://github.com/publiccodenet/standard/issues/267

**Comment by ericherman** [comment]
No doubt, there remains lots of room for improvement on the questions, but I suggest that we close this initial issue with an eye to incremental improvement on the list via smaller pull-requests.
