### ISSUE TITLE
Suggest adding activity "help to set up git repos" on Founding Membership Proposal

### ISSUE THREAD

**Issue by imingueza** [publiccodenet/about#332]
In https://docs.google.com/document/d/1icscB-9jPUF2psL1pm8mM_53BKQ5gEIKqmHnsTicKKY/edit#heading=h.1jgdrb5p9tzh
I would like to propose to add a bullet point with the text “Help to set up Git repos” in section “The Foundation for Public Code’s activities will include” (page 3, 1st column).

Cities' managers can lose time if they don't know how to do correctly, so can be very helpful.

**Comment by clausmullie** [comment]
Great suggestion! 

I would add this to the [About page](https://about.publiccode.net/activities/codebase-stewardship/for-existing-projects.html) which is the 'source' from which the template is made from. Feel free to make a pull request for this.

In the future we could then perhaps develop a guide for this as part of our [trainings](https://about.publiccode.net/activities/trainings/)

**Comment by clausmullie** [comment]
Somewhat addressed by the [repository template](https://github.com/publiccodenet/repository-template)

**Comment by bvhme** [comment]
And also of course the blog post on [How to start a Standard compliant GitHub repository](https://blog.publiccode.net/news/2020/12/09/how-to-start-a-standard-compliant-repository.html).
