### ISSUE TITLE
Update privacy notice with information about how we handle partner data

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#336]
...once we have member data to handle!

This data will probably include:
- names
- job titles
- addresses

What about:
- org financial (probably not covered by GDPR since it's not an individual, but there are [Dutch data retention laws](https://www.tuxx.nl/bewaartermijnen/documenten/#Algemene%20bedrijfsmatige%20documenten) that apply to business records)
- information received because of the association member status (so dues admin) (also required to be kept by Dutch law)

Assumption: our members will value us being hyper transparent about how we handle all of our admin and which national laws we comply with, so that they can use this info to square it legally on their side

**Comment by ElenaFdR** [comment]
@demkodo, this looks like something you/we could start thinking about!

**Comment by demkodo** [comment]
When time and space allow, I want to think about this in a broader context, namely include expanding the [section on About on member relations](https://about.publiccode.net/activities/member-relations/) with the outcomes of the [meeting we had about the practical aspects of member onboarding](https://hackmd.io/HHLXhV_XTpupEkxKFPIO5w?edit). "How we handle member data" involves several people at different stages from first contact onward, with each involved person focusing on different goals (e.g. membership dues, codebase stewardship, facilitate involvement with assembly). Therefore we need a consistent, repeatable process, e.g. when first contact with a prospective member is made, does that same person need to make sure the data we need is gathered and added to Odoo CRM? Or, do we do this after the fact, and if yes, how, when and who? Let's have meeting with the staff involved with membership soon to look at expanding About member onboarding, as well as template how we gather and process the member data and who's responsible / monitoring. Once that is clear we can update the privacy notice accordingly.

**Comment by ericherman** [comment]
As the nature of membership is changing, this is no longer applicable in the same way. Perhaps it can be re-opened if needed for the chapters.
