### ISSUE TITLE
Publish English membership contract and foundation bylaws

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#340]
Publish an English version of the template Foundation membership contract so that potential members' legal teams can start to review.

Steps:
- [x] create English version of [membership contract](https://drive.google.com/open?id=1Qm6g0xW0zO-4SG4EIzJInFQYcj7ZKGEV1NO8DYkeTbU)
- [x] create English version of [foundation bylaws](https://drive.google.com/open?id=1ljm0J-6e5QkWFNPHmbx4yRr5fzGjKoO8QkSZb7uH6Gk)
- [ ] ~~check both with lawyer~~ Willemijn advises that as the Dutch original is the only version that matters in Dutch court, we publish these as informal translations until someone requires a formal translation. (She's looked at both as a former lawyer and considers them credible.)
- [x] put into Markdown and publish

**Comment by clausmullie** [comment]
This also requires the English translation of our association bylaws

**Comment by ElenaFdR** [comment]
After reviewing this, @clausmullie and I think this won't be controversial - the draft membership contract only asks members to abide by the foundation bylaws. This means that getting the English translation of the bylaws up is the higher priority.

**Comment by ElenaFdR** [comment]
These still need review by a lawyer, but here are the draft English versions of:
- [membership contract](https://drive.google.com/open?id=1Qm6g0xW0zO-4SG4EIzJInFQYcj7ZKGEV1NO8DYkeTbU)
- [foundation bylaws](https://drive.google.com/open?id=1ljm0J-6e5QkWFNPHmbx4yRr5fzGjKoO8QkSZb7uH6Gk)
