### ISSUE TITLE
Create narrative frame for founding membership pack

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#342]
This should build on the content in the [founding membership proposal](https://about.publiccode.net/activities/member-relations/founding-membership-proposal.html).

We currently think this includes:
- executive summary
- "we're building the Foundation together"
- "here's what it's going to cost" (based on #324)
- "challenge: how are we going to do this together?"

This wraps around:
- #340
- #341

**Comment by clausmullie** [comment]
Closing this, as the 'founding membership' phase is over.
