### ISSUE TITLE
Set up a (GDPR compliant) mailing list for members and community

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#350]
This builds on both a channel strategy to define what we want to communicate with who, as well as the technical backend of how we will manage lists.

**Comment by clausmullie** [comment]
@ElenaFdR can we close this issue now that we have a [mailing list](https://docs.google.com/forms/d/e/1FAIpQLSdOArHWz6leVrOdOLcVlm9nbgKSrn5gxAgCIytZsAWgqnkbWQ/viewform)?

**Comment by ElenaFdR** [comment]
I still need to write instructions for other people within the org on how to use our mailing list in order to keep it GDPR compliant.

**Comment by clausmullie** [comment]
I feel like [this page](https://about.publiccode.net/activities/tool-management/mailing-lists.html) now contains a good set of instructions for mailing list administrators. Ok to close, @ElenaFdR ?
