### ISSUE TITLE
Devise and publish a procurement policy for the Foundation

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#372]
Steps:
- [ ] find out what Dutch law requires (eg, what paper trail do we need for tax purposes?) (See also the [VNG model procurement policy](https://vng.nl/onderwerpenindex/recht/aanbesteden/nieuws/geactualiseerd-model-inkoop-en-aanbestedingsbeleid), which is apparently widely used)
- [ ] work with team to identify our values when it comes to procurement (eg, do we care about the provider being non-discriminatory, environmentally sustainable or a local business?)
- [ ] look at the values/constraints of the procurement policies of potential members so we're relatively consistent (at least in values, even if we don't have the same legal constraints)
- [ ] create a draft (for example, this is a [quite staid English-language template](https://www.fundsforngos.org/ngo-operational-policies/4-procurement-policy-for-ngos/))

**Comment by bvhme** [comment]
I think this issue goes about it quite heavy handed, and I like the proposal for now better in #643.
