### ISSUE TITLE
What is a good license for this repository?

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#4]
I'm doubting the usefulness of copyright here, so I'm leaning CC0, however perhaps we want to have some bounds on replicating the entire organisation.

Ideally I'd like it to be possible for people to 'fork' the Foundation if they need improvements.

**Comment by bvhme** [comment]
For now, as per #22 and what we've discussed in last weeks Directors meeting we're going with CC0. If anyone has an idea on the implications of this we would love to hear it.

**Comment by chartgerink** [comment]
What's the scope of the content licensed CC0? My personal preference usually is CC0, so I am inclined to say that anything you develop would be good under that license because it maximizes reuse and potential impact :)

**Comment by bvhme** [comment]
Yep, I like that. I have put the logo, the main thing I didn't want to licence CC0 in a separate repo http://github.com/publiccodenet/brand

I think we can move ahead with CC0, and make the public code public domain.
