### ISSUE TITLE
Clarify Assessment criteria and Standards requirements divergence

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/about#403]
Assessment criteria care about community distribution, while the Standard only requires 'multiple parties'.

This difference is _fine_ in reality, but it should be clear about why this extra depth is important to stewardship.

**Comment by Ainali** [comment]
Perhaps not exactly the content of this issue, but the title was, at least partly, addressed by #577.

**Comment by clausmullie** [comment]
The standard is canonical, should be timeless, and I think is solid as is.

The assessment criteria are developed more iteratively (we are currently revising our intake process), serve more as guidance than a yes/no question (continued conversations with codebase communities) and ultimately will be a decision taken by members.

With this reasoning, I propose to close this issue, and update our assessment criteria as we iterate on them.
