### ISSUE TITLE
Move 'goals' to marketing site 

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#404]
These [goals](https://about.publiccode.net/organization/mission.html) predate the founding of the Foundation. While a nice description of the future we're working towards, these don't contribute to our shorter term prioritization or further our understanding of how to get there.
We've concluded they would be a better fit for the marketing site.

**Comment by bvhme** [comment]
This has been closed in #644. The goals were not moved though. I'm closing this issue, but @ElenaFdR if you think we should put those goals on publiccode.net we can move this issue there.
