### ISSUE TITLE
Product marketing stewardship: list of questions for discovering existing assets in a code maintaining org

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#416]
For purposes of brand building for a codebase, it'd be good to extract this information from any codebase users/replicators:

* business cases
* stats
* success stories
* quotations
* any existing marketing/PR/press

Create a shareable question list to help find the people who have this info.

**Comment by clausmullie** [comment]
I am closing this issue as I feel we have a) developed our thinking and experience further in this domain, b) have the codebase page on our homepage and c) have websites for two codebases. This means we already have developed templates for the kind of information we need.

Business case is the only item not covered yet, but this is a recurring difficulty, relies on data availability and most likely needs to be done per codebase. Large enough in scope to warrant its own issue next time we try make one.
