### ISSUE TITLE
Vendor relations not included on About

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#417]
See bullets under support stewardship [here](https://about.publiccode.net/activities/codebase-stewardship/activities.html).

On the [https](https://publiccode.net/codebase-stewardship/) we do include:
> We also help vendors such as cooperatives, NGOs and for profit companies to sell, implement and support the product.

**Comment by bvhme** [comment]
It would be great to include this

**Comment by Ainali** [comment]
It feels like it is partly included in the bullet point Marketing, but it could perhaps be more explicit.

**Comment by clausmullie** [comment]
Closed with #422
