### ISSUE TITLE
Investigate options for hosting mailing lists (and other codebase tools)

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#423]
From the session about the top 20 in publiccodenet/jekyll-theme#30 it was discovered that we should look into maybe hosting some sort of mailing lists for codebases that are under stewardship. @ericherman and I will look into that.

**Comment by ericherman** [comment]
we should consider buying maillist hosting services

https://wiki.list.org/COM/Mailman%20hosting%20services

**Comment by Ainali** [comment]
Yes. Buying the service relieves us from having to do sys admin and backup of it ourselves. Perhaps we should do a quick session for a set of requirements that we would have on such a service and then look around to see what is available?

**Comment by Ainali** [comment]
So after a short meeting we came up with the following short list of requirements:

* It should look like we are hosting the lists (eg. lists.publiccode.net)
* We should be able to administer lists and create new when needed
* No limits on subscribers
* Public searchable email archive should be included

**Comment by Ainali** [comment]
So based on the requirements above, I looked at [the list on the mailman site](https://wiki.list.org/COM/Mailman%20hosting%20services) and found some alternatives that all seem to be good enough:

* https://www.a2hosting.com/web-hosting/compare **3,37€/month**
* https://power-netz.de/webhosting **€5/month**
* https://www.minuskel.de/nc/hosting/preisliste.html **29,75€/month**
* https://maadix.net/en/servers **150€/year** (entire server)

I suggest we start out with the first one, setting up a list for the standard and see how it works out.

**Comment by bvhme** [comment]
I agree, @Ainali could you see which one fits [our procurement principles](https://github.com/publiccodenet/about/blob/develop/activities/procurement/principles.md) the best? Then let's go for that one.

**Comment by Ainali** [comment]
@gmarpons This is my previous research. I misremembered that there were any totally free mailman hosts. I cannot find any here or in my browser history that does it free of charge.

**Comment by Ainali** [comment]
Just a note that I am actively having this on hold until I can explore how the mailing lists in Odoo works. If it fulfill our [requirements above](https://github.com/publiccodenet/about/issues/423#issuecomment-538311479) we should consider using it.

**Comment by Ainali** [comment]
It turned out that what I thought could be mailing lists in Odoo only was email campaigns in [the Email marketing app](https://www.odoo.com/page/mailing-features). With that settled I will go ahead with Power Netz that seems closest to our procurement principles.

**Comment by Ainali** [comment]
I updated the requirements after good input from @bvhme. Search continues.

**Comment by ElenaFdR** [comment]
Based on @Ainali, @demkodo and me reviewing the [list of early incubation product assets](https://about.publiccode.net/activities/codebase-stewardship/product-assets-for-early-incubation.html), we'll need vetted tools we can recommend (and deploy promptly) for: codebase repository hosting, marketing website hosting (we're currently missing templates for static Jekyll sites), community fora, documentation hosting (if the codebase is extensive enough), issue tracking and roadmap.

**Comment by ElenaFdR** [comment]
A related need is to have examples we like of how other open source codebases have set up their tooling, so a codebase considering adopting a new tool can see a range of perfectly reasonable options. 
@Ainali also mentions having a mechanism for getting a codebase a domain name.

**Comment by ElenaFdR** [comment]
#521 is a related ticket.

**Comment by demkodo** [comment]
Made an overview of the community tool needs and possibilities. Let's mule it over and plan a moment to see what the next best step can be. Information on the quote, setup and possibilities, including other options can be found here:
https://drive.google.com/drive/u/0/folders/1U1n60VSpnLhKneYaZfIGjf7Te2-WzKVj

There are no other hosting companies that I know of that can provide these services, so Greenhost is our best shot. Greenhost has not offered Discourse and Phabricator before so we can discuss a custom setup for this with them. An alternative is doing the 'basic' services such as provisioning (sub) domain names, Mailman mailing lists, VPS'es for GitLab and Bitbucket at Greenhost, and have Discourse and Phabricator hosted and serviced on premises at these companies themselves.

**Comment by Ainali** [comment]
Very nice, thanks @demkodo!

So we really only need Discourse for our own purposes immediately. The other ones can be put on hold for now until we see more of a concrete need in codebases that are incubating. (Me and @ElenaFdR were quite convinced by [Matt Broberg's talk at FOSDEM](https://fosdem.org/2020/schedule/event/nextgencontributors/) that it is superior to mailing lists and therefore that we should start with just that.)  Perhaps setting this up deserves to be broken out to its own issue?

Continuing on this issue, we should probably start taking notes on our experiences with different tools and hosting alternatives so that we can point codebases that have not made a commitment towards stewardship yet to good solutions. Open questions around that is: where to store such a list and what does it need to include to be useful?

**Comment by Ainali** [comment]
#350 is a related ticket.

**Comment by Ainali** [comment]
@demkodo I guess we can close this one now?

**Comment by clausmullie** [comment]
We now have a functional mailing list, checked with @demkodo  - this can be closed :tada:
