### ISSUE TITLE
Ecosystem vs. Codebase clarity

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/about#427]
Stewardship says "Only at the ecosystem level" other places we say "Codebase" let's clarify this. In the process, let's spell out the boundaries of what we mean by "Codebase" with regards to repositories, forks/branches, fora, etc.

This should be useful in helping ourselves and others to understand and explain the boundaries of our responsibilities.

**Comment by clausmullie** [comment]
Glossary items include:
* [ecosystem level](https://about.publiccode.net/glossary/ecosystem-level-definition.html)
* [codebase](https://about.publiccode.net/glossary/codebase-definition.html)

**Comment by clausmullie** [comment]
On reviewing this issue, I do not think we should define the boundaries of our responsibilities through the glossary. The glossary should be for clear and concise definitions, ideally timeless ones.

The boundaries of responsibilities of our work will change over time, steered by the codebases and members we work with, and the general development of the organization. This is probably better captured on other pages on About, such as [codebase-stewardship/activities.md](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/activities.md).

Alternatively, focal areas for our ambitions should maybe belong somewhere like organization/mission.md.

That being said, my sense is we can close this issue. The definition for ecosystem is solid. We are currently working with codebase communities and public organizations to identify how best to support them, so our responsibilities may change, and we should capture this in our activities pages accordingly. 

@ericherman what are your thoughts? Good to close?
