### ISSUE TITLE
Activities performed in codebase stewardship lacks sufficient detail

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/about#428]
For each of the four pillars we have bullet lists of activities, however each bullet lacks a description of what it is, why it is important, what the foundation does, and what are the Foundation responsibility boundaries.

https://about.publiccode.net/activities/codebase-stewardship/activities.html

**Comment by clausmullie** [comment]
Once people understand the general boundary of our work (see issue #427) it might be useful to explain why and how our activities will make their codebase succesful.

For each activity, we could include a few sentences on:
1) typical situation in open source
2) what are the opportunities?
3) what are the risks?
4) what does the Foundation do/value we create?

**Comment by Ainali** [comment]
Agreed. Each activity should probably have its own resource with the things @clausmullie mentioned plus one or more guides on how to actually do those activities in a repeatable and predictable manner.

**Comment by clausmullie** [comment]
@Ainali @ericherman I feel we can close this issue - what do you think?

**Comment by Ainali** [comment]
Yes, or keep it as an EPIC. In my opinion each bullet point should have its own index.

**Comment by clausmullie** [comment]
Ok, will close this for now. We can later convert each subheading from #431 into a separate index when we add in more content.

**Comment by clausmullie** [comment]
Also, this conversation is continued in #439
