### ISSUE TITLE
How can you plead for "international sanctions" wrt open-source ?

### ISSUE THREAD

**Issue by gibello** [publiccodenet/about#434]
The `CONTRIBUTING.md` page mentions publiccode "follows EU laws regarding international sanctions".
Do you mean that states we don't consider as democracies should have no access to open-source ? Or are you afraid that "terrorists" distort "democratic" code ? Or is it a question of "morals" ??
It is likely that open-source brings democracy, increases culture and literacy. And even if not, who are we to decide what's evil and what's not ? We are the ones who write the book, not the censors...
So, I think you should remove that sentence about sanctions: really, sanctions have nothing to see with open-source !

**Comment by Ainali** [comment]
Thanks for reading so closely and for caring for open source. The sentence you refer to is not intended to be a statement about open source in general, nor is it a requirement for codebases adhering to the Standard for Public Code. 

This sentence applies to the legal body of the Foundation for Public Code. We are registered as an association in the Netherlands, and thus must comply with local laws and regulations in this jurisdiction. This includes abiding by the sanctions that are in effect in the EU.

**Comment by bvhme** [comment]
I suggest changing the wording in the `CONTRIBUTING.md` for now to reflect this. I propose #435 for now.

@gibello if you have any more questions also feel free to email us/me at <info@publiccode.net>.

I feel this resolves this issue, to close it.
