### ISSUE TITLE
Add governance exercise as a guide

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#437]
Copy the documentation for the governance exercise to About. We need to find a place to link it from. Is perhaps a further reading section on the page with [product assets for early incubation](https://github.com/publiccodenet/about/blob/develop/activities/codebase-stewardship/product-assets-for-early-incubation.md) a first good place?

**Comment by bvhme** [comment]
I'd say that 'workshops' can be an 'activity we perform and this workshop can live under that. This will also give us a nice menu of workshops to pull from and point to.

**Comment by Ainali** [comment]
So add a link to it from https://about.publiccode.net/activities/ as well or rather move the entire exercise there?

**Comment by Ainali** [comment]
fixed by #444
