### ISSUE TITLE
Arrange Hacktoberfest 2019 event

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#438]
Sunday 27/10 12.00-17.00
* Create buzz
  * [x] Event page (meetup?)
  * [x] List at Digital Ocean
  * Tweets
    * [x] first
    * [x] friday 25
    * [x] sunday 27
* Fix food
  * [x] snacks (some more crackers @Ainali )
  * [x] soft drinks (some soda @Ainali )
  * [x] beer
* Signs
  * [x] More WIFI signs

**Comment by Ainali** [comment]
Event is up on MeetUp: https://www.meetup.com/Code-For-NL/events/265766965

**Comment by bvhme** [comment]
Yay, very well done Jan! I like this :)
