### ISSUE TITLE
Add documentation needed to operationalize codebase stewardship

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#439]
## Aim:
We are currently starting with the assessment and incubation of our first codebases (:tada:). 

## Need
Our existing documentation can be improved to support the operationalisation of codebase stewardship. The first iterations can be our hypothesis, which we iteratively adapt as we progress with codebase assessment and incubation. 

## We currently have:
[Standard for public code](https://standard.publiccode.net) which outlines the end state we want to bring a codebase to
[Criteria to assess codebases](https://about.publiccode.net/activities/codebase-stewardship/criteria-for-codebase-stewardship.html) which outlines what we look at when considering a codebase for incubation
[Stewardship for existing projects](https://about.publiccode.net/activities/codebase-stewardship/for-existing-projects.html) which gives codebase owners a sense of what codebase stewardship would look like in operation
[Assets for early incubation](https://about.publiccode.net/activities/codebase-stewardship/product-assets-for-early-incubation.html) which gives our codebase stewards an indicative list of what assets should be created around a codebase 

## To operationalise stewardship may want to consider developing first iterations of:
- [ ] A list of codebase user needs/user stories - see #440
- [ ] An indicative estimate of resourcing required from us and others involved in stewardship - see #441
- [ ] A guide for codebase stewards on how to get started on a codebase

**Comment by bvhme** [comment]
This is a good high-level issue, however it needs some more distilling into workable chunks to be useful. The last section is great for that!

**Comment by clausmullie** [comment]
Pull request towards this final step includes guide for starting assessment #520

**Comment by clausmullie** [comment]
Stewardship has now been operationalised. These are still good ideas, but will close for now.
