### ISSUE TITLE
Add a codebase stewardship resourcing estimation model

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#441]
## Need
We are currently operationalising codebase stewardship on the first set of codebases

As part of this, 
* we want to estimate our capacity and progress as we steward a codebase
* codebase maintainers and contributors want to know how much incubation will cost them in time/money to they can prepare/plan the requires resources and staff

Additionally, 
* we want to gather data to help build a 'Cost Model' for the Foundation that helps us project member dues to codebases in stewardship

## Initial proposal
'Absolute' estimation of time/cost for action items is very difficult, as we have no/little existing data and each codebase is unique - with it's own needs, community, and existing maturity level. 

We could use a 'relative' tracking system in which we rank each action item on a logarithmic scale - so 2 being 'quickest', 4 twice as 'long', and 8 twice as 'long' as 4 - for both our involvement and that of "the others". If we feel 2x is to small in increment we could do 4x and 10x as well.

The advantage with relative time tracking is that progress early on in the lifecycle of a codebase and be used to estimate for future items (so if it took us 60h to complete 16 points worth of tasks, we/others can estimate we might need 150h to complete the remaining 40 points worth of tasks on that same codebase).

**Comment by bvhme** [comment]
Hey Claus,

Do you mean this as codebase specific or one general list, as I think these estimates probably vary wildly per codebase.

**Comment by ericherman** [comment]
Jan and I did some "t-shirt sizing" on a codebase to see if we thought the effort was /likely/ (based on our imperfect view) to be "small", "medium", or "large" for each item. Roughly I thought that "small" items could be accomplished in a day by a pair of people, that "medium" items could be accomplished in a week by a pair of people, and "large" items would take longer.

While I believe there are going to be similarities, I am certain it will vary a lot by codebase. That said, looking at the trends may be useful for initial estimation.

**Comment by bvhme** [comment]
Do we still think this is for now, or shall we close it until it becomes urgent again?

**Comment by clausmullie** [comment]
I think this will happen organically, so can be closed as issue.
