### ISSUE TITLE
Rethink styling in governance exercise

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#457]
In [this commit](https://github.com/publiccodenet/about/pull/444/commits/4eeede09a51739674bb287787c13161c0beed940) I removed html elements from the markdown file to make it adhere to good practice and standard. However, testing showed that those styling were useful to see differences from the first part of the session. Rethink how the user can get useful clues in a way that doesn't introduce styling in a markdown file.

**Comment by bvhme** [comment]
Fixed by #444
