### ISSUE TITLE
How do we ask questions to our contributors/advisors?

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#47]
I would like GitHub issues to be the place where we can work together with our contributors/advisors in order to solve the problems at the root of this foundation. I'm imagining inviting those who have been willing to advise us to specific issues and asking them to engage with more from there.

I think the goal of individual Issues is to:
* Identify what the foundation should be, do and communicate: what the contents of the repository/site should be
* Spawn new issues with questions and work that needs to be done

I'm trying to figure out: 
* how can we ask questions in a way that is conducive to conversation 
* and that engages our contributors/advisors?
* And what should the subject line
* and the body text contain?

I've made these issues which can serve as examples to discuss this:
* #27 How can we sustainably fund the Foundation so it can be a long-term partner?
* #32 For who are we doing this?

So, what should a good issue be, and what should it do? @chartgerink @nebster do you have any ideas?

**Comment by chartgerink** [comment]
I figure that specifying terminology in the title goes a long way. What is long-term? What are you doing? making this kind of information explicit will help guide contributors into the issue with a clear picture of what is being discussed.

I'd also suggest maintaining good survey question rules, for comprehensibility:
* Only single barreled issues (no X and Y issues)
* No negations in the issue title
* Issue title should be self-contained (related to remark above)
* Try to mitigate subjective interpretation (also related to remarks above)

**Comment by bvhme** [comment]
I think this is clearly defined now in the `CONTRIBUTING.md`
