### ISSUE TITLE
move large files out of repo into separate location/repo

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/about#470]
As raised in https://github.com/publiccodenet/about/pull/461#pullrequestreview-312399224 we have some large files (like 33MB .odt files which have embedded fonts) which might be better outside the repository. This is especially true for files which do not naturally "diff -u" well.

**Comment by bvhme** [comment]
I think, knowing more about Git, that storing files this large might just not really make much sense in Git for now. Every clone gets all the history and with multiple of these files it could balloon out of proportion. We could enable [Git-LFS](https://git-lfs.github.com/), however that might complate things.

For now, I think larger files are best left versioned elsewhere.

**Comment by ElenaFdR** [comment]
We now use [Nextcloud](https://about.publiccode.net/activities/tool-management/nextcloud.html) for this. It looks like the only .odt files left are for the [governance exercise](https://about.publiccode.net/activities/supporting-codebase-governance/exercise/) (cc @Ainali). Are there any other large files anyone's aware of?

**Comment by Ainali** [comment]
No, I am not aware of anything else (is it possible to search a repo by file size?). And those files should really move to Nextcloud.

**Comment by Ainali** [comment]
We talked about this briefly in our weekly stewards meeting. A problem with Nextcloud is to keep track in there what files are being referred to from external pages. If we move them around or rename them links might be broken. The same might happen if we change from Nexcloud to something else or (less likely) if we change provider.

An alternative would be to have a separate repository for only the large files. This would bring the advantages of git while still keeping the 'regular' text dominated repository light weight.

Which of these, or any other, alternatives do we prefer?

**Comment by clausmullie** [comment]
> If we move them around or rename them links might be broken. 

Wouldn't GitHub Actions alert us to broken links?

**Comment by Ainali** [comment]
Yeah, GitHub actions only warn for our own internal links, not incoming links from around the web.

**Comment by ericherman** [comment]
Newly added links are [checked](https://github.com/publiccodenet/about/blob/develop/script/cibuild.sh#L2) on each pull request.

There is a full [link-check](https://github.com/publiccodenet/about/blob/develop/.github/workflows/link-check.yml#L28) which runs separately. The emails contain many [false alarms](https://github.com/publiccodenet/about/runs/4687202037?check_suite_focus=true) but we do check them to make sure.

I expect links to assets will be linking to them from where they are deployed, not to the repository, thus which repository they are extracted as part of the build should not impact this much.
