### ISSUE TITLE
Codebase in the glossary might be confusing

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#473]
I'd like to report an issue in `glossary/codebase-definition.md`

> This can be in the form of – for example – a document or a version-control repository.

I would make clear that these are just places where these things live, not what they are. So perhaps this can be:

> The codebase can be stored in – for example – a document or a version-control repository.

**Comment by ericherman** [comment]
Maybe we should change the text to simply be:

> Codebases are typically stored in a version-control repository.

**Comment by clausmullie** [comment]
Careful, as this glossary item may have to explain more than just this. See #427 - if we decide to use 'codebase level' as a critical marker of differentiation from other municipal associations, as well as the boundary of our activities, then either this glossary item or a new one for 'codebase level' needs to be strong enough to self-explain this clearly. 

Content we could build on for this exists in #431 - where we added it to the activities page to give our community a sense of the type of role we take.

**Comment by clausmullie** [comment]
In light of this issue #281 I think we should keep 'codebase' as the 'item' we perform our activities on, and split this from 'codebase level' which designates the boundaries or space in which we perform our activities.
