### ISSUE TITLE
How do we label issues so that advisors can spot the issues they are aligned with?

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#48]
If we're inviting advisors to take part in our conversations here on the GitHub issues, how do we get them to find the issues that make sense to them.

I propose labels like `contributor engagement` or `community management` and `financial` etc. However I don't know if any of these make sense.

How would this connect to the advisors you have in mind @nebster?

**Comment by ElenaFdR** [comment]
Closing because we don't know what categories of help we'll need yet. We'll generate this taxonomy once we have more data.
