### ISSUE TITLE
Create a structured pipeline management process

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#485]
This includes:
- what the stages are
- what our actions are at each stage
- frequency of actions
- relevant resources
- how we make sure new contacts are promptly added to Odoo

It should be based on and be integrated with Odoo.
This should supersede the current [member relations index about page](https://about.publiccode.net/activities/member-relations/), which is a mix of resource info for potential members and guide for us:

**Comment by lscheske** [comment]
Closed by #616
