### ISSUE TITLE
Structured community consolidation process

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#487]
Devise a process to make sure:

- new people's contact details are definitely captured
- new people we meet are invited to relevant community fora (mailing list, community calls?)
- we follow up with them in a timely fashion
- we connect them to other people or info they're interested in
- people already in one of our communities know of opportunities to join others (deepen community engagement)

Relevant existing content:
- [guide to attending events](https://github.com/publiccodenet/about/pull/482)

**Comment by clausmullie** [comment]
## Webinar series
We could also consider hosting or chairing a series of online webinars for our community on:
* How to procure open source effectively (Daniel Menil from Kammarkollegiet has done great work on this) 
* Successes and challenges of municipal collaborative open source collaborations (eg with Rasmus from OS2 or Miquel from Cloud4Cities, and perhaps some of the Dutch networks we are working with) 

## Recommended events
* We could perhaps consider compiling a list of interesting events/webinars on code quality or one of the 4 codebase stewardship activities which we would like to attend/learn from, and invite our community to join us

## Show love to our community's codebases
* We could organize a mini hackaton for staff members to give some love to repo's in our community and prospective members

**Comment by Ainali** [comment]
I believe the original purpose of this issue was closed by #566. @clausmullie do you want to break out some of the things you added to separate issues?

**Comment by clausmullie** [comment]
Fine with closing this. But will tag @AlbaRoza and @ElenaFdR in case the webinar series idea is useful for them.
