### ISSUE TITLE
Affiliates are not explained

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#496]
We don't really explain anywhere what it means to be an affiliate. It could go into the glossary, and perhaps also be a resource or guide where templates could be linked.

**Comment by clausmullie** [comment]
Same for becoming a partner. 

We list these both as user groups in our [value proposition mapping](https://about.publiccode.net/activities/value-and-impact/user-mapping/), and in our [roadmap](https://about.publiccode.net/organization/roadmap.html).
