### ISSUE TITLE
Partners are not explained

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#499]
We don't really explain anywhere what it means to be an partner. It could go into the glossary, and perhaps also be a resource or guide where templates could be linked.

We list both partners and affiliates as user groups in our [value proposition mapping](https://about.publiccode.net/activities/value-and-impact/user-mapping/), and in our [roadmap](https://about.publiccode.net/organization/roadmap.html).

_Originally posted by @clausmullie in https://github.com/publiccodenet/about/issues/496#issuecomment-555545331_

**Comment by clausmullie** [comment]
Discussion was had at length in #687 and #660, closing this and those were also closed.
