### ISSUE TITLE
Explore using Odoo as our tool to track interactions with potential members and codebases

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#501]
## This issue 

To achieve our mission, we interact with a lot of members and codebases. 

We have achieved the levels of interaction with potential members and codebases where we need a structured tool to track these interactions.

This issue is to explore evaluate using Odoo as a tool to track interactions with potential members and codebases.

## The next steps are to: 

- [x] Define principles for our tracking, based on existing principles for our organization, communication and data retention
- [x] Identify our tracking needs
  - [x] Collate our needs for data tracking based on our existing interactions with potential members
  - [x] Collate our needs for data tracking based on our pre-assessment of codebases
- [x] Research what Odoo offers as a solution, to understand what functionality it offers (particularly re linking data, tagging, sort/filter, etc)
- [x] Develop a draft data model
- [x] Test this data model with one or two use cases
- [x] Evaluate whether Odoo may be useful for tracking existing members and codebases in stewardship
- [x] Decide whether to invest in migrating all potential member and codebase data into Odoo

## Existing resources
To identify our needs: 
* Notes in hackmd.io and emails
  * Notes include: Nordic trip notes, Dutch download, Proposal-stage organizations
* Information not written down 
* Issue #485 to define the structured process for our interaction

Outdated proposal for a data model #247 
 
Outdated [Foundation information megamap](https://docs.google.com/spreadsheets/d/1rSdYZARvbJ7TNuKExVgAoCs1SeXQoNYNP_mTid6nP_E/edit#gid=0)

## Notes
Existing members and codebases in stewardship have been purposefully left for a later step, as they will most likely fall under different principles, and we are not currently doing this yet.

**Comment by Ainali** [comment]
#246 refers to a guide about blogging, not a data model. What should the link be to?

**Comment by clausmullie** [comment]
Yes indeed :D Should be #247, have fixed above.

**Comment by clausmullie** [comment]
We are now using Odoo for this, so will close the issue
