### ISSUE TITLE
Split run a community call into three parts?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#504]
When I just added a template for invites I realized that the page is quite long already, and that it is also missing some parts which would make it even longer. That made me believe it should be split up into three separate guides; one for before, during and after respectively. They could all be linked from the new resource (from #495) that explains community calls. Is this overdoing it or does it make sense?

**Comment by Ainali** [comment]
When splitting them like we decided on in the call on 19 December, and with the new Odoo setup, some more instructions is needed as well, which makes this even more called for. Unless anyone has objections (@ElenaFdR ?), I'll go ahead.

**Comment by clausmullie** [comment]
@Ainali  can we close this issue,  now that we have 2 separate community calls - one for Standard for Public Code and one for Foundation for Public Code?

**Comment by Ainali** [comment]
Quite the opposite in my point of view. I think it would be of even greater help now, since there is going to be different processes preparing for the calls. But if no one else agrees I hesitate to continue.

**Comment by bvhme** [comment]
If you think it is useful I'd go ahead.
