### ISSUE TITLE
Should we have some documentation about updating about on About?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#508]
I am thinking both the actual process of building and deploying in detail, but also meta level things such as the recurring "Prune the about" meeting and how we want things to be reviewed before merging. Perhaps the [Documentation](https://github.com/publiccodenet/about/blob/develop/activities/documentation/index.md) could be expanded?

**Comment by bvhme** [comment]
@Ainali, there have been some updates to the README (information on building and deploying) as well as to documentation on structure. Has this resolved this issue, or are you looking for something else?

**Comment by Ainali** [comment]
@bvhme I believe this was solved with #561, closing it now.
