### ISSUE TITLE
Markdown renders "" as typographical “”

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#509]
This breaks the process for creating new assessments sheets as documented on https://about.publiccode.net/activities/codebase-stewardship/create-assessment-spreadsheet.html

**Comment by bvhme** [comment]
Then you are writing code.

To create a codeblock in markdown you can use backticks \`, for example

```markdown
| A1 | B1 | C1 |
| -- | -- | -- |
| `=CONCATENATE("=";B1;C1;""")")` | `IMPORTRANGE("https://docs.google.com/spreadsheets/d/1R4cngGioU3u8gZDp_MdcHUeS234NOfqZxKGfLGiJGtw/edit","TEMPLATE!` | C3 |
```

Renders as

| A1 | B1 | C1 |
| -- | -- | -- |
| `=CONCATENATE("=";B1;C1;""")")` | `IMPORTRANGE("https://docs.google.com/spreadsheets/d/1R4cngGioU3u8gZDp_MdcHUeS234NOfqZxKGfLGiJGtw/edit","TEMPLATE!` | C3 |
