### ISSUE TITLE
Name for a community place?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#521]
This is perhaps a bit premature, but let's put it out here to simmer. If we were to have some sort of forum like Discourse or phpBB for our community to discuss topics of their interests, what should we name that subdomain? Ideas that are floating are generic like: community, forum or discuss or more specific named after the tool used. Any points of view on this?

**Comment by clausmullie** [comment]
I like the idea of community.publiccode.net!

**Comment by clausmullie** [comment]
Tangentially linked to #487. This fora could be one of the places to which we drive people and engagement.

**Comment by bvhme** [comment]
I assume we would rather keep the word community for our entire community wherever it is, not just one medium.

I like forum or lists, or using the name of a solution like discourse.

**Comment by ElenaFdR** [comment]
I enthusiastically support using a plain English description of the tool, like 'forum'.
I advise against using the tool brand - it's meaningless for people who haven't encountered the tool before, and it makes it harder to migrate to another tool in the future. It's also a problem if the tool owner decides to rebrand or expand their current brand to unrelated tools.

**Comment by fbartels** [comment]
How about:
- talk.domain
- discuss.domain
- some online communities use help.domain, but that does not seem fitting here

**Comment by ElenaFdR** [comment]
We've chosen discuss.publiccode.net based on an informal poll.
