### ISSUE TITLE
Activities vs organization

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#550]
I find it a bit confusing that the page with all [internal org stuff](https://about.publiccode.net/activities/staff-management/) is under Activities rather than Our organization. Does anyone else feel the same?

**Comment by bvhme** [comment]
The logic behind this is that `organization` is information and properties of our organization, how we do things should all be under `activities`. This so `organization` can be owned by everyone and be slow moving whilst `activities/*/` can be owned by specific teams and move quickly.

I've tried to put that into [`about-folder-structure.md`](https://github.com/publiccodenet/about/blob/develop/activities/documentation/about-folder-structure.md), however that might need some improving.

**Comment by bvhme** [comment]
@Ainali do you have anything to suggest we can do about this or shall we close the issue?

**Comment by Ainali** [comment]
I think we can close it.
