### ISSUE TITLE
Add 'contributing on behalf of' to our standard PR template for stewarded codebases

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#562]
WHAT: Recommendation by @jredding, following his FOSDEM talk about [Engaging Enterprise consumers of OSS](https://fosdem.org/2020/schedule/event/enterpriseoss/) ([plus Twitter precis](https://twitter.com/miss_jwo/status/1223973101999939587)) on how best to integrate occasional or short term contributions by people employed to work on a codebase.

WHY: gives maintainers more visibility of why people are contributing to their codebase, which helps them plan their feature and technical roadmaps, plus understand which companies are employing people to contribute to a codebase (and therefore whether those people might join the long term community or just abandon code and disappear).

HOW: Here's [Github's page on how to do this](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-on-behalf-of-an-organization).

**Comment by Ainali** [comment]
This could possibly go into a recommendation to the Standard, but if not, we should have it as a recommendation to all the communities we steward. 

What could possibly go on about is that we as staff should use it as well when we contribute to repositories, even if it is just during our "show our communities some love" sessions. Perhaps adding that as a page is a spin-off from this. What do you think @clausmullie ?

**Comment by Ainali** [comment]
And to respond to the actual suggestion. If I understand Githubs help page correctly, these are not added to the PRs (and thus cannot go in the template) but directly on the commits.

**Comment by clausmullie** [comment]
+1 to @Ainali 's proposal of testing it out ourselves in our contributions to codebases

**Comment by clausmullie** [comment]
@ericherman is this something to consider integrating into the standard, codebase stewardship, or our own practice? Or can we close this issue for now and keep it in the back of our minds?

**Comment by ericherman** [comment]
As this is a GitHub convention, I'd suggest it's a "keep in the back of our minds" and also to watch how widely it becomes adopted.

**Comment by clausmullie** [comment]
Ok, sounds good. As it has been open for a while without activity, I second closing it for now.
