### ISSUE TITLE
Post process FOSDEM 2020

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#563]
From [attending events](https://about.publiccode.net/activities/events/attending-events.html) (if you're done, or have nothing to do, tick your box):

## Upload photos
Into the folder **Public, sharing outside enabled/Communications/Events and stock photos/FOSDEM 2020**

- [x] Alba
- [x] Boris
- [x] Claus
- [x] Elena
- [x] Eric
- [x] Jan

## Process all expenses for the event.

- [x] Alba
- [x] Boris
- [x] Claus
- [x] Elena
- [x] Eric
- [x] Jan

## Process all new contacts for the event.

- [x] Alba
- [x] Boris
- [x] Claus
- [x] Elena
- [x] Eric
- [x] Jan

## Evaluate if the goals set for the event were met.

- [x] Alba
- [x] Boris
- [x] Claus
- [x] Elena
- [x] Eric
- [x] Jan

## Retrospective
On Thursday?

**Comment by clausmullie** [comment]
@Ainali will close this issue as we had both our debrief and retro meetings. Please reopen if you feel it is still relevant.

**Comment by Ainali** [comment]
Let's have the person clicking the last checkbox close the issue. As a reminder, ping @ericherman @bvhme @AlbaRoza @ElenaFdR @clausmullie, please when you are done with one activity, or have nothing to do, tick your box.
