### ISSUE TITLE
Adding a question to 'Join our community' form

### ISSUE THREAD

**Issue by AlbaRoza** [publiccodenet/about#568]
Add the question "How did you get to know the Foundation?" to our [mailing list form](https://docs.google.com/forms/d/e/1FAIpQLSdOArHWz6leVrOdOLcVlm9nbgKSrn5gxAgCIytZsAWgqnkbWQ/viewform).

This action would help us understand where our subscribers come from and boost activities in successful forums.

**Comment by Ainali** [comment]
Just a note that our mailing list form now exists [in Odoo](https://odoo.publiccode.net/survey/start/594b9243-c7e5-4bc1-8714-35137c971842).

**Comment by clausmullie** [comment]
@Ainali I have added a line to the survey - "How did you find out about us". Good to close this issue? Or any tweaks to be made?

**Comment by Ainali** [comment]
I think that is good enough!
