### ISSUE TITLE
Add Sustainable Development Goals to our value proposition

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#572]
add it to:
- senior civil servants
- residents and journalists

Add it to https://about.publiccode.net/activities/value-and-impact/.

@bvhme wrote for somewhere else:

To illustrate the impact of a healthy public code ecosystem on basis of the Sustainable Development Goals, we contribute towards: 
- goal 16, ‘Peace, Justice, and Strong Institutions’, with transparency, quality public service delivery and participation
- goal 11, ‘Sustainable Cities and Communities’, by enabling sustainable collaboration on digital transformation at scale
- goal 9, ‘Industry, Innovation, and Infrastructure’, by enabling new collaborations between public and private parties
- and of course goal 17, ‘Partnerships for the Goals’

**Comment by Ainali** [comment]
**Yes!** Adding some bullet points for the different stakeholders and then an entire page linked from Value and impact that explains how we believe our work is aligned with some of the Sustainable Development Goals would be awesome. For some municipalities I think it will be a really helpful way to see our value addition in a larger picture.

**Comment by ElenaFdR** [comment]
Adding this rhetoric in other places on about/orgnization or http may also help confirm our non-profit status. (For example, @demkodo could use this for a US equivalency determination).

**Comment by lscheske** [comment]
I wholly support this, I think especially as @nebster 's conversations with the likes of UNDP develop, they will like hearing us speak their language. 

I think this is valuable for a number of our user groups, and would therefore support @Ainali 's point on having an entire page on SDG's.

Decision makers and sponsors:
- political
- senior civil servants
- structural funding and philanthropy

Other interested parties:

- end users (residents and citizens)
- journalists and academia
