### ISSUE TITLE
Create about/activities/communication/talks

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#575]
Create a page with a list of hyperlinks to:

- videos of presentations we've given
- any tweets or blogposts about that talk (which ideally includes a nice summary of the talk contents or impact)

**Comment by Ainali** [comment]
#543 is a little bit related. 

Another thing that touches upon this; As a matter of transparency, should we have a comprehensive list on all the public talks/presentations/workshops that we have been doing (whether or not there are video, slides or other resources from the event)?

**Comment by Ainali** [comment]
When we do this, we should remember to add instructions in [attending events](https://about.publiccode.net/activities/events/attending-events.html) and [organizing events](https://about.publiccode.net/activities/events/organizing-events.html) that this list perhaps can be updated.

**Comment by bvhme** [comment]
My suggestion would be to add this as a category to the Blog as there is less need for this to be canonical information and it fits well into that context.

**Comment by Ainali** [comment]
Fixed by publiccodenet/projects#16
