### ISSUE TITLE
Offer more tangible examples of what we see as Public Code

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#58]
I've been asked to describe, especially for new contributors, what public code is.

There might be something we can take from the Smart Cities? Public Code! repository for this.

**Comment by bvhme** [comment]
Perhaps this is a great addition to the Glossary of #29

**Comment by nebster** [comment]
Perhaps referencing https://www.decidim.barcelona/ or https://github.com/Amsterdam/panorama

**Comment by jenvandermeer** [comment]
In contrast to closed murky opaque owned code.

**Comment by ElenaFdR** [comment]
Closing because so far no potential members have asked for this; we'll reopen this when someone definitely tells us they would find this useful.
