### ISSUE TITLE
Add new index for helping set up governance under activities

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#582]
We are moving forward with many codebases and it will become very useful to have some published materials on what governance encompasses. Set up an index page that explains the topic and includes

- [x] references to where we explain parts of governance elsewhere (if any)
- [x] link to and brief explanation of the governance exercise
- [x] link to and brief explanation of the governance game
- [ ] template for governance model
- [ ] list of further reading

**Comment by bvhme** [comment]
I think this is very important, although I would like to stress, everywhere, that **we don't do governance**, we support it.

As this comes up again and again and I feel we need to keep convincing people we're not going to run away with the codebase or get controlling power in some governance board.

I'd say our activity can be something like 'governance support' or 'governance execution' or something, but not governance itself, that is what the stakeholders need to do.

[I'd even like to ask to change the title of this issue to prevent confusion]

**Comment by Ainali** [comment]
> I think this is very important, although I would like to stress, everywhere, that **we don't do governance**, we support it.

A really good point to stress! I have changed the title of the issue and will make sure it is really prominent everywhere.

**Comment by Ainali** [comment]
Here is one good resource for further reading, possibly even for making an archetype: https://github.com/opengovernance/opengovernance.dev

**Comment by bvhme** [comment]
That seems like a great resource to add to the Standard _further reading_ section.

**Comment by Ainali** [comment]
Solved by #584
