### ISSUE TITLE
Should community calls be recorded? No. Chatham house rule even?

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#605]
We've just had a short conversations on the question of whether it would be nice to publish recordings from our community calls.

We find that people speak more frankly when they are not and we want them to be open.

This lead us to believe we should maybe institute something like the [Chatham House Rule](https://en.wikipedia.org/wiki/Chatham_House_Rule) in our meetings.

Should we?

**Comment by Ainali** [comment]
It's a really good question. The argument that the discussions will be more frank is strong. However, as an organization made up of other public organizations, I feel that being transparent with who attended is appealing. I think our current practice with giving everyone a chance to not feel misrepresented strikes a decent balance. If we have a really controversial topic, perhaps only then we could implement the Chatham house rule specific to that meeting?

**Comment by bvhme** [comment]
The Chatham House Rule could still apply even though we publish a list of
attendees. It would just mean that we never connect a name to a position or
quote.

At least as I understand it.

**Comment by Ainali** [comment]
I think that would be a "house rule" on top of the Chatham house rule, as the original is quite explicit "but neither the identity nor the affiliation of the speaker(s), _nor that of any other participant_, may be revealed." (my emphasis).

**Comment by bvhme** [comment]
Ah, yes, then we shouldn't phrase it like that! Good catch.

**Comment by ElenaFdR** [comment]
Can this issue be closed?

**Comment by bvhme** [comment]
Do we not want to act on this?
