### ISSUE TITLE
Clarity in emails and scheduling

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#607]
There are a lot of emails and meetings right now, and it might be hard to get an overview when they have subject or names that could be applicable to several different codebases.

Suggestion to easier give an overview we could prefix them with the codebase name. 
Example: Instead of having a meeting named "Shared backlog items" it could be named "Signalen: Shared backlog items"

Does this make sense? Is [Codebase:] a useful prefix?

**Comment by bvhme** [comment]
Personally I'd rather see this happen in practice (making it part of our culture) then in policy (making it part of our process). Since I don't feel it is that valuable to enforce this.

**Comment by Ainali** [comment]
And how would you like the culture to be? Prefix, suffix, make it clear through a natural language subject line? Personally, I would prefer something that can be filtered and/or easily searched for.

**Comment by bvhme** [comment]
As i'm guessing this is also something that has to bleed into the outside world I'd use something natural that doesn't conflict with other solutions like lists, so no `[]`. 

For this reason I think the prefix with `Project name: ` is probably the best. Clear for everyone, feels natural.

This should be sufficient for filtering needs as well.

**Comment by Ainali** [comment]
Ok, and with that, I'll close the issue!
