### ISSUE TITLE
Adding info about Discuss on About

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#608]
This is a tracking issue for adding necessary resources about [discuss](https://discourse.publiccode.net/) on About. A new hire should be able to find information about how we want to use the tool.

Resources needed to be updated or created:

- [ ] Dedicated page about how to use it and what the purpose is
- [ ] Mentioned in [communication](https://about.publiccode.net/activities/communication/)
- [ ] Point in [How to staff](https://about.publiccode.net/contributor-guides/for-staff.html)
- [ ] Mention in membership somewhere

Is there something else that is immediately needed?

**Comment by ElenaFdR** [comment]
Not for About: we could write a blogpost about why we've taken this step, so that our goals for discuss.publiccode.net are public.

**Comment by Ainali** [comment]
Closing inline with #763
