### ISSUE TITLE
Consider creating webinar series

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#611]
## Webinar series
We could also consider hosting or chairing a series of online webinars for our community on:
* How to procure open source effectively (Daniel Melin from Kammarkollegiet has done great work on this) 
* Successes and challenges of municipal collaborative open source collaborations (eg with Rasmus from OS2 or Miquel from Cloud4Cities, and perhaps some of the Dutch networks we are working with) 

## Recommended events
* We could perhaps consider compiling a list of interesting events/webinars on code quality or one of the 4 codebase stewardship activities which we would like to attend/learn from, and invite our community to join us

## Show love to our community's codebases
* We could organize a mini hackaton for staff members to give some love to repo's in our community and prospective members

_Originally posted by @clausmullie in https://github.com/publiccodenet/about/issues/487#issuecomment-554320275_

**Comment by clausmullie** [comment]
## Additional ideas
* Podcast/webinar on 'technical steering' and 'community health' (separately) including codebase stewards and the members of codebase communities we work with that are responsible for the respective topics

**Comment by felixfaassen** [comment]
Great tool to facilitate live webinars is https://www.crowdcast.io/ (not open source unfortunately) also useful for organizing virtual conferences and has a lot of integration options.

**Comment by clausmullie** [comment]
As we now have a regular podcast and community calls, are hosting the FOSDEM public code dev room, regularly contributing talks to conferences, and occasionally have single-issue one-off workshops on the topics described above, I will close this issue. At this point, it creates more clutter without creating much value.
