### ISSUE TITLE
Add new content to "Member Relations" page

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#618]
Under About > Activities:
* Update "Member Relations" page with content based on: [Membership Process](https://hackmd.io/fAEK_CulTO2oH1dinSzEXg), and

**Comment by bvhme** [comment]
As to the name, activities should have the name of activities :) I think if we name an activity 'membership process' it should be to 'process the members' :p

Also, understand that activities can be built out of other activities. So for instance all these can exist next to each other:

* Activity 'member growth'
* Activity 'membership development'
* Activities like 'member events' and 'general assembly' could also exist
* Activity 'member relations' could list that it is the combination of all of the above.

**Comment by lscheske** [comment]
In this case, I would propose that we then keep the title "Member Relations" and add the new content outlining the "process" from the HackMD file to that page. The intro blurb can easily replaced with: "Member relations entails..."

At this point, I would not want to split the process into separate activities on the main activities page, since they are all part of "member relations". The page should provide a brief overview of what member relations entails. Once we develop individual activities further, we can decide to build separate activity pages.

**Comment by lscheske** [comment]
Closed with PR #738
