### ISSUE TITLE
Add "Stakeholder Engagement" page with new stakeholder definitions

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#619]
To About > Activities

Add "Stakeholder Engagement" page with new stakeholder definitions [Stakeholder Engagement](https://hackmd.io/3ikgA_8OSOCxWeix6y4i7w)

**Comment by bvhme** [comment]
I think this needs a bit more work to figure out how to turn this into operational processes.

First of all, if it is about 'stakeholder engagement' the activity should likely contain the processes for us to deal with all of our stakeholders, not just those mentioned in your document. So these still need to be broken up into meaningful 'activities'.

Next to that this document contains a whole lot of new processes, phrasing, and constructs that need to be formalized and decided on. This means that one big pull request would almost certainly be very hard to merge and discuss well on.

For this reason, the way to move forward with this is translating the proposals from the document in a set of pull requests that can then be individually be merged. Alternatively, it could probably work well if you turn a lot of the proposals from the document into issues first so they can be discussed before we make pull requests for integrating it into the whole.

I know this seems like a lot, however, I think it is up to us to make these changes well and well documented. Not rush into them. I believe if we build this we need to build a solid operational machine which means having clear and considered processes.

**Comment by lscheske** [comment]
Ok, I propose that we start with agreeing on these definitions and putting these into the glossary. Once we start having more of an idea of what activities with non-member stakeholders (partners, affiliates, commercial partners) look like, we can develop separate pages for those. 

My thought behind this is having a single page that briefly describes what our stakeholder groups are, without going into too much process detail.

@ElenaFdR what are your thoughts on this?

**Comment by ElenaFdR** [comment]
As mentioned in our call yesterday, I suggest 2 different ways of presenting information about the people we work with:
- as a persuasive invitation on publiccode.net: orgs we work with are presented through exciting case studies, quotations, stories on the blog, pretty photos, all backed up by a 'how you can get involved' call to action (which is the only place we explain that there are different categories of stakeholders)
- as operational information on about.publiccode.net: clear information for anyone involved in membership development or other stakeholder relations about the categories, their definitions, any category-specific assets (for example the case for sponsoring one of our events and the contract for it), and especially our responsibilities to that category (or the permitted scope of our activities for that action - for example, we'll probably develop guidance on how we talk about or showcase a single vendor of a multi-vendor codebase, so it doesn't look like we're especially endorsing them above their competitors).
