### ISSUE TITLE
Outdate/remove old membership templates

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#621]
Add OUTDATED disclaimers to: 
- [Membership onboarding support](https://about.publiccode.net/activities/membership-growth/member-onboarding-support.html)
- [Founding membership proposal template](https://about.publiccode.net/activities/membership-growth/founding-membership-proposal.html)

The idea is to add a disclaimer in the title of these pages so that it is clear the content is old, but to still keep the links alive, since we have shared them with people over the past year. 

Alternatively we could remove from about entirely and have them live on in our git history. The content lives on in the new "membership process" page and the proposal template will be revamped into something we actually use now.

**Comment by bvhme** [comment]
I'd remove what is no longer true. If something is still true but for a small number of people it is worth adding some information that explains that. I would not keep things around for reference outside of the Git history.

**Comment by lscheske** [comment]
Agree! I like the idea of cleaning up content and only having what is currently "true" on our About.
