### ISSUE TITLE
Create new template for member proposal

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#622]
We currently have two templates that have similar content, none of which completely fit our current process:
- [Member onboarding proposal](https://docs.google.com/document/d/1G-pOyoMvHCjSzMt8YiI6dj7tmP4v9Mbd9sthTyM9pCA/edit)
- [Founding membership proposal template](https://docs.google.com/document/d/1G-pOyoMvHCjSzMt8YiI6dj7tmP4v9Mbd9sthTyM9pCA/edit)

Idea is to create a new, single template that serves as the cover/TOR of the contract, and make this part of the membership contracting step. We will recycle most of the old content.

**Comment by bvhme** [comment]
Hey @lscheske, what is a TOR?

I'm looking forward to reviewing the updated content.

**Comment by lscheske** [comment]
@bvhme TOR: Terms of Reference, which describes activities/deliverables, which typically accompany the contract itself, which is all the legal jargon.
