### ISSUE TITLE
Create 'Core Deck - Open Belgium Edition'

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#631]
Publishing is blocked by #575

**Comment by clausmullie** [comment]
This was added to the list in [projects.publiccode.net](https://github.com/publiccodenet/projects/blob/develop/talks-and-articles.md)

**Comment by Ainali** [comment]
> This was added to the list in [projects.publiccode.net](https://github.com/publiccodenet/projects/blob/develop/talks-and-articles.md)

Ah, I perceived it to be slightly different. I thought this was meant to create a new template presentation based on the Open Belgium presentation, rather than just publishing those slides.

**Comment by clausmullie** [comment]
Aha I had misunderstood - would you like to prioritise and reopen this issue? Or leave it closed?

**Comment by Ainali** [comment]
Well, I am not sure that I had it right. :)
