### ISSUE TITLE
Improve knowledge transfer between Codebase and Membership Teams

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#632]
Since we now work primarily in our two thematic teams  (Codebase Stewards, Membership Developers), some of the knowledge and information transfer has gotten lost. Are there any ideas of how we can ensure that both teams are up to date on each others work?

**Comment by ElenaFdR** [comment]
Just to clarify: do you mean regular updates on a team's work, or a team's evolving approach/big picture strategy?

**Comment by lscheske** [comment]
I mean regular updates on team's work e.g. where do we stand with codebase projects, where are we with members xyz. 

Hadn't thought about the big picture strategy, I think it would be worthwhile to also have an exchange format for that!

**Comment by lscheske** [comment]
Closing because #639 is all encompassing.
