### ISSUE TITLE
What are our relationships to others in the field, what foundations and public administrations work in this field

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#64]
It would be great if we could create a list of related organisations, and how we can complement them :)

So if you know any other public technology organisations or communities please tell us who they are and how they could relate to the Foundation For Public Code.

**Comment by nebster** [comment]
These are the sort of issues that seem to beg a larger question, which is "where does this sort of strategic, possibly informally generated information, live in a open, fully tracked organizational formation?"  Do we track these organizations just in the comments to this issue, as markdown possibly publicly facing, as a link to an external spreadsheet?

**Comment by bvhme** [comment]
Perhaps we should be thinking about how we can 'formalise' this kind of information. 

For instance, we could solve this by asking people from other organisations how they see their possible relationship with us (perhaps after talking this through with them) and then we can make that an open document (a page on the site) that illustrates our position in the landscape.

**Comment by jenvandermeer** [comment]
Causal maps - co-create with local partners - in a given city. What's the cause and effect of policy and actions and how implementing a public code approach improves the public benefit. Then with your partners describe who owns what contribution to code, code-derived services, and resulting benefit.

**Comment by Beanow** [comment]
Hello from https://sfosc.org/!
> This is a place dedicated to the discussion, creation, and evolution of Sustainable Free and Open Source Communities. We are organized around the development of a set of shared principles that we believe lead to healthy, sustainable open source communities.

Looks like Public Code and SFOSC have a lot in common. Many of the goals and ideas around what sustainable communities look like are embedded in what you're doing here. While we're not focused on the public sector, there should be plenty of overlap we can work together in. Feel free to reach out on the repo https://github.com/sfosc/sfosc I'll also have a look around here to see if I can help.

**Comment by bvhme** [comment]
Hey @Beanow! We definetely have a lot in common, we're planning to figure out how to learn effectively from what you're doing :)

**Comment by ElenaFdR** [comment]
Closing because so far no potential members have asked for this; we'll reopen this when someone definitely tells us they would find this useful.

**Comment by bvhme** [comment]
As a reference @alex-fsfe just started this project: https://github.com/alex-fsfe/fs-policy-europe/wiki

(Also, closing)
