### ISSUE TITLE
Clarify Product Management with the Stewardship roles

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/about#642]
"Product Management" or "Product Marketing"

The activities page focuses on the marketing aspects of product and not the "making it a real product, not just a kit":

https://about.publiccode.net/activities/codebase-stewardship/activities.html

@clausmullie @Ainali @AlbaRoza @felixfaassen

**Comment by Ainali** [comment]
It's not only that page, also this one: 
https://about.publiccode.net/activities/codebase-stewardship/explaining-stewardship/codebase-product.html

I guess we should decide whether or not both marketing and management is part of the Product pillar and then perhaps make a wider sweep on the entire site and make sure that we actually say what we want include.
