### ISSUE TITLE
The header 'We need you' on the homepage can be clearer

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#65]
The heading for the contributing section on the homepage (in `index.md`) is 'We need you', which I think can be clearer :)

## How to fix this issue

1. Open [`index.md`](https://github.com/publiccodenet/about/blob/develop/index.md)

2. Edit the header reading 'We need you' to something a bit clearer, like for instance 'How you can contribute' or 'How you can help us'

3. Make a Pull Request with your changes

🎉

**Comment by ElenaFdR** [comment]
Closing because this appears to be an obsolete issue.
