### ISSUE TITLE
Missing philanthropic fundraising as an activity

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#657]
Our model is now built on collecting philanthropic funds. We lack however the public documentation for this.

I imagine the `activities/philanthropic-fundraising` folder to contain:

* Information on how to gift through the King Badouin Foundation US fund.
* Information on how to gift in the Netherlands through the ANBI status.

**Comment by demkodo** [comment]
Yes, indeed. I'll work on it :) thanks

**Comment by bvhme** [comment]
💪 If you want to commit to doing this @demkodo, feel free to 'assign' it to yourself in the right sidebar :arrow_right:

**Comment by ElenaFdR** [comment]
Closed by #672.
