### ISSUE TITLE
It is unclear in the README what the file for the homepage is

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#66]
If someone comes in and wants to edit the [home page](https://about.publiccode.net) they need to edit the file `index.md`. 

However, if you don't know about the web, how can you ever know...

Ideally the `README.md`, which displays as the file that displays on the GitHub repository home page explains what file to edit for the homepage on the website.

## How to solve this issue

1. Open the file [`README.md`](https://github.com/publiccodenet/about/blob/develop/README.md)

2. Add a mention of the homepage on the `about.` website is in the file `index.md`. You could add a sentence under the "Preview, Build and Deploy" heading explaining this.

3. Submit a Pull Request!

🎉

**Comment by clausmullie** [comment]
@bvhme does it still make sense to *only* explain that the homepage is editable via the `index` file? Or would #1055 and #1056 help people enough on their way to contributing?

**Comment by clausmullie** [comment]
I am going to close this issue. The user journey for someone not familiar to GitHub would be to look at the page and click on the `edit this page` button. If they want to dive deeper, they have the extensive contributing documentation.
