### ISSUE TITLE
Deploying before the weekend comes with the risk of being called out of bed

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#664]
Our current process is to release changes to `about` at least every Friday. However, if there is a problem with what we've pushed it means we might need to spend time on the weekend to fix it instead of during the workweek.

@ElenaFdR, would you be willing to change the weekday for releases.

**Comment by ElenaFdR** [comment]
Of course!

**Comment by bvhme** [comment]
My suggestion would be Monday actually. With the week ahead of us :)

**Comment by ElenaFdR** [comment]
Great minds, etc.

**Comment by bvhme** [comment]
You mean 'Great minds think alike, though fools seldom differ'?
