### ISSUE TITLE
Membership gating criteria in Odoo are outdated

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#667]
We are currently not abiding by the gating criteria in our CRM in Odoo. The membership process varies considerably from the criteria currently listed. The gating criteria need to be updated. I propose the following steps:

- [x] Identify "gates" that are "set in stone" based on our Articles of Association and Membership Contracts
- [x] Laura make proposal in this issue, Membership Team discuss here
- [ ] Update the membership process (steps) based on the findings

See also #666

**Comment by bvhme** [comment]
Top! I like this approach. May I suggest separately doing thesse things and also implementing them separately (separate PRs).

**Comment by bvhme** [comment]
Oops, I misread this title. The above comment I meant for our documentation, not specifically for the gates in Odoo.

**Comment by lscheske** [comment]
@bvhme Yes! In fact the first two check-boxes are "offline" research work, which will manifest in the actual updating of the process (third box), which will be done in a PR & updating the Odoo kanban. 

So with this issue I tried to represent the main steps needed to get there, even if they happen off-git.

**Comment by bvhme** [comment]
Awesome! :rocket:

**Comment by lscheske** [comment]
**Proposal for new "gates", applied in Odoo and for the membership process in general:**

* **Not for now**
Organization cannot pursue membership at the moment.
* **Opportunity**
New contacts, informal exchanges via email, chat, or at events.
* **Lead**
Introductory meeting with organization that is followed up with an email containing more information on us & membership.
* **Proposal**
Membership proposal sent. Further discussions on membership input & benefits for organization. Ends with agreement on the proposal.
* **Contracting**
Membership contract sent. Further discussions on contract details, membership dues, and legal issues.
* **Member**
Membership contract signed. Membership dues received. 
> In our current practice, proposal & contracting are happening simultaneously, with the proposal being an explanatory document to the legal contract. We could also combine the two, with the understanding that "contracting" is a phase that many organizations stay in for a long time, and in which we do a lot of "pinging".

**Current "gates" in Odoo:**

* **Not for now**
Description: Said not for now
* **Backburner**
Description: Wait until 2020
* **Opportunity**
Description: Introductory email or chat
* **Lead**
Description: First meeting with stakeholder that ends with EOI sent
* **Interest**
Description: EoI Signed
* **Proposal**
Description: To enter: Fully fledged membership proposal sent. Ready for next stage when membership proposal is agreed.
* **Contracting**
Description: To enter: membership contract is sent. Ready for next stage when contract is signed.
* **Member**
Description: Membership dues are received

**"Gates" in Articles of Association:**

5.1. A public organization wishing to become a member submits a request to the board of directors.
5.2. The board of directors decides on the admission as soon as possible and informs the relevant public organization of its decision without delay.
5.3. Joining of a new member shall be laid down in a membership contract to be drawn up by the board of directors.

**Comment by bvhme** [comment]
Awesome, that's really good! It's good to have this overview. I also like this proposal.

How do you think that the 'gates' from the articles of association relate to the proposed gates?

**Comment by lscheske** [comment]
> How do you think that the 'gates' from the articles of association relate to the proposed gates?

Glad you like the proposal! I put those articles from the AoA in there just to show which articles might have an effect on the membership growth process. I actually think that there is not a very strong relation at the moment. We could incorporate the "request to the board of directors" into the "Proposal" stage, just to have it formalized. This is not yet relevant to where we stand now as an organization, but will hopefully be necessary once more organizations want to become members, and we have to do a stricter evaluation of their aims/values etc.

**Comment by Ainali** [comment]
> * **Proposal**
>   Membership proposal sent. Further discussions on membership input & benefits for organization. Ends with agreement on the proposal.
> * **Contracting**
>   Membership contract sent. Further discussions on contract details, membership dues, and legal issues.

It seems like there is a theoretical possible "limbo" where there is an agreement on a proposal, but no membership contract has been sent. Avoiding gates in both ends is a way to avoid this. Do we really need them both or can one be removed?

**Comment by lscheske** [comment]
> Do we really need them both or can one be removed?
As per my comment in the post, this (the sending of these documents) indeed happens in the same step currently.  The membership proposal is more like an explanatory document/terms of reference that accompany the contract.  I would also be for turning this into one step.

Do others agree? 

@nebster @bvhme @clausmullie

**Comment by lscheske** [comment]
The new gate could then be: 

**Contracting**: 
Contracting documents (Membership proposal and Membership contract) sent. Further discussions on membership input & benefits, contract details, membership dues, and legal issues. Ends with agreement on document content and signing of the Membership contract.

This will then be the stage that many organizations will be in for a long time.

**Comment by bvhme** [comment]
That makes sense.

The sending of the contract can be trivial since it's text is available on about and they could potentially sign it without us sending it to them :) I think the agreement on the proposal is the important bit.

Possible change not necessary now: We have talked in the past about having the 'proposal' not be a proposal but a 'jointly' created 'membership plan', which was a document in which we would describe what membership meant for both, made together, basically the proposal but then less of us imposing it. Also, for niceness, I like the idea of this being a plan and not a contract. That way the contracting gate can stay as it is and one of both parties can then go sign the contract.

**Comment by lscheske** [comment]
Ok, I am applying these changes to Odoo now! 

New gates: 

* **Not for now**
Organization cannot pursue membership at the moment.
* **Opportunity**
New contacts, informal exchanges via email, chat, or at events.
* **Lead**
Introductory meeting with organization in which interest in membership is indicated. Followed up with an email containing more information on us & membership.
* **Contracting**
Contracting documents (Membership proposal and Membership contract) sent. Further discussions on membership input & benefits, contract details, membership dues, and legal issues. Ends with agreement on proposal content and signing of the Membership contract.
* **Member**
Membership contract signed. Membership dues received.

**Comment by lscheske** [comment]
Changes have been applied.
