### ISSUE TITLE
Changing our terminology so that is is "racially neutral"

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#668]
GitHub just announced that it will be abandoning terms that are racially insensitive (see this [BBC article](https://www.bbc.com/news/technology-53050955)) such as "master" and "slave" or "blacklisting" and "whitelisting". I think we only use this term for our "master" branch. Shall we get with the times and rename this to "main" "primary" or "final" to avoid using oppressive terminology?

This is also linked with the e-mail that @demkodo sent around recently.

**Comment by bvhme** [comment]
This is great to hear. I suggest we make this change as soon as GitHub publishes whatever they've made the default to make sure we stay in line with it and reduce complexity for new contributors.

**Comment by Ainali** [comment]
On the topic, there is this great Red Hat community talk on Welcoming nomenclature: https://www.youtube.com/watch?v=hZuFeFuazwo accompanied by these slides: http://tm3.org/et 

But why is this labeled invalid? This issue seems to me to be both as a correct observation and important.

**Comment by Ainali** [comment]
> This is great to hear. I suggest we make this change as soon as GitHub publishes whatever they've made the default to make sure we stay in line with it and reduce complexity for new contributors.

The new default is `main`, but GitHub [recommends](https://github.com/github/renaming) waiting for new tools to make the change as smooth as possible. Or are our repos small enough to just move ahead?

**Comment by lscheske** [comment]
> > This is great to hear. I suggest we make this change as soon as GitHub publishes whatever they've made the default to make sure we stay in line with it and reduce complexity for new contributors.
> 
> The new default is `main`, but GitHub [recommends](https://github.com/github/renaming) waiting for new tools to make the change as smooth as possible. Or are our repos small enough to just move ahead?

I agree with this entirely, Jan, and I think that we shouldn't wait for tooling to move ahead with with this quick change. I can't technically do it - @bvhme @ElenaFdR @nebster , could you guys help out here?

**Comment by ElenaFdR** [comment]
We've done this now for all repos except the Jekyll theme, which we'll do as soon as the remote Jekyll theme plug-in is updated (see [issue 66](https://github.com/publiccodenet/jekyll-theme/issues/66)).
