### ISSUE TITLE
Do Presentations and Explainer videos belong in About repo?

### ISSUE THREAD

**Issue by nebster** [publiccodenet/about#68]
Given that we are trying to maintain the about repo and thus about.publiccode.net as a "canonical truth" about the organization, does it make sense that more production intensive and harder to update materials live inside, or in another more ephemeral repo like the main site.

Thinking about using reveal.js for presentations using the slides.com editor.

**Comment by bvhme** [comment]
I think we should opt for keeping canonical information in this repo and try to only have information in here 'once' (DRY)

So like the http site having it's own repo I can imagine pitches and presentations having similar versioning mechanisms.

Can we close this issue?

**Comment by nebster** [comment]
I suppose so!
