### ISSUE TITLE
The help we give public organizations outside of codebase stewardship is not an activity

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#681]
We provide a lot of informal help to the organizations we work closely with that does not directly fall under codebase stewardship or any of our other activities, nor works directly towards membership in a clear and tangible way. 

Examples of this work are:

* giving feedback on proposals as experienced open source people,
* connecting various members in our community that are working on similar affairs,
* guiding people to resources useful for their journey, and
* explaining how to do public code and open source development well in public organizations.

**This is intended** and the help we give is not meant to be a discrete activity. However, it is not clear why that is so.

If we look at our [cultural values](https://github.com/publiccodenet/about/blob/develop/organization/cultural-values.md), the most obvious here is the 'Helpful' value, however 'Trust' and 'Community' are just as relevant.
These are incredibly valuable to the relations we need to build in order to deliver on our [priorities](https://github.com/publiccodenet/about/blob/develop/organization/mission.md#current-priorities) and proving our assumptions.
In order to prove we can do what we say we need to show we know what we're doing, are on their side, and have the right connections for a community role.

Being helpful shouldn't be an activity we offer, it's in our DNA. Helping people out is a part of being a professional in this field.

Next to that, we don't want to be a consultancy nor do we want to compete with consultancies, as if others can do it why should we. We provide the help that we think moves us towards our [mission](https://github.com/publiccodenet/about/blob/develop/organization/mission.md) at our discretion.

This can be illustrated by how we interact, as:

* we do not provide consulting services, as we don't create deliverables or take responsibility, and
* we don't provide it on contract, but only if and when we think it is meaningful for furthering our mission.

Sidenote: this is besides whether we might in the future add activities that do provide more structural support to other organizations.
For now, I think structuring this 'helpful' aspect of our relationships can seriously restrict our ability to work towards our mission and harm the trust we've built so far.

Proposed solution: expand the [cultural values](https://github.com/publiccodenet/about/blob/develop/organization/cultural-values.md) with an 'example' of what these principles mean in practice.

**Comment by bvhme** [comment]
In other words, as a clarification: 

Being helpful is at the core of what we do, and is not restricted to our members or codebases. We are helpful throughout our community with all organizations/people we engage with. We build a lot of the trust needed in membership development and codebase stewardship by helping organizations with informal help. 

Membership or codebase stewardship is the end goal, and not any delivery or fulfilment of a service.

We do not have a formal activity for this because currently:

* we don't want to limit what we can do to get members or codebases into stewardship (focus on mission)
* we don't want to (and cannot) be consultants (anti-competitive)
* we don't want this to be a perk (anti-competitive)
* we don't want to make commitments or set expectations for these things (focus on mission)

**Comment by nebster** [comment]
I have quite a different view of this matter.  I believe we have been overlooking a core pillar of our work.  Our mission is to build an ecosystem for public code.  Right now, our entire set of activities are focused on codebases.  But an ecosystem is full of both codebases and organizations.  I realize that attention to organizations will arise "emergently" from work with codebases, but we need to recognize that there are explicitly activities we perform around digital transformation process for organizations as well.  Helping them understand how to participate and plan for engagement with public code resources, or even embark on a public stewarded project. This work is not anti-competitive in the same way that software and policy stewardship are also contextual engagement with both public organizations and market 3rd parties to arrive at procurement and maintenance that makes sense for every actor [and we are not in any way a transactant]. 

In thinking further about this issue, I think we can describe digital transformation process itself as a codebase, much like the market consultation or governance game or even this about are "codebases".  There can in turn be a Standard for Digital Transformation Process, that we run the 'request for comment/participation' on which involves both public and private actors in its definition.  In fact, you can replicate the whole stewardship activity network on the process side, with all four streams represented.

I realize we ourselves do not officially have capacity for this type of work currently, but we do much of it now and it remains unrecognized.  I think by making it explicit, we will be able to speak to public organizations that are theoretically interested in our work, but do not understand how they can get to the orientation and capacity necessary to participate.  I believe this is crucial for widening the scope of potential membership by public organizations.  

This may need to be a longer term capacity development on our part, but in the meantime I believe we can already formalize some of this through recognition of Member Development as a core activity.  Membership development is outreach, but there is also a component of our engagement with public organizations in the pre-member stages [possibly called "partners"] that is about helping them understand the often initially complex set of issues regarding transformation toward public code adoption and building capacity in their own departments to adapt to this new way of working.

**Comment by bvhme** [comment]
I don't think these views are opposed. Developing shared community assets is and should be an output from being helpful. We informally help a lot of people solve their own issues which gives us the insight needed to either develop the assets that can help with this, or enable a community to solve these problems themselves.

I do think we can be better and more effective at this is being helpful is a trait of how we do our work and not a separate thing that we do.

What I'm trying to prevent with making it part of our cultural values over a discrete activity is that I want nobody to think this is not their job.

We're here to help. But not to do your work for you.

**Comment by bvhme** [comment]
The other side of this is that we're working towards our priorities, those are now to get members, codebases, and philanthropic funding. Making (or facilitating the creation of) 'digital transformation tools' is not a goal on its own right, it should be done in the pursuit of our priorities.

**Comment by nebster** [comment]
These views are not opposed, no.  They are differing ways of expressing how we achieve our priorities.  I see the stewardship of 'digital transformation codebases' as an explicit activity of our first priority, which is gaining members, some of whom need to transform to participate.  The explicit activities within this stewardship are of equal priority to those around software and policy codebases. Thus, Member development / stewardship as an explicit prioritized activity.

**Comment by nebster** [comment]
To your other point above, I think the situation in which people feel like we will do their job can be diffused by our approach of "process codebase" provision, which are instructions, template materials, and learning resources for transformation and capacity building activities, but not ones we execute for the public administrations.  We can eventually also maintain a "support" community of consultative market parties that we can direct public organizations towards if they require explicit practice engagement.

**Comment by clausmullie** [comment]
@bvhme and @nebster do either of you see a concrete change or issue you would like to surface? 

My sense is that this was an interesting reflection and discussion - and great to see this in the open. But I am slightly lacking a sense of how actionable this is. My sense is that this is part of the ongoing growth development of the organization. We have since made several changes to how we work, and no doubt will continue to do so. My sense is this issue can be closed for now, and revisited if/when needed.

**Comment by clausmullie** [comment]
Closing this issue, as per comment above!
