### ISSUE TITLE
Add in reusable workshop assets based on OpenZaak market consultation workshop

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#685]
This includes the business model and risk assessment workshops.

Business model:
- [x] Index
- [x] Agenda
- [x] Canvas
- [x] Guide
- [x] Merged

Risk assessment:
- [x] Index
- [x] Agenda
- [x] Canvas
- [x] Guide
- [x] Merged

**Comment by clausmullie** [comment]
Note: I have explicitly excluded the 'market consultation questions and answers' part from this issue. I propose that instead of investing energy to make a 'template' here, we can invest that energy in making the [OpenZaak market consultation repo](https://github.com/open-zaak/open-zaak-market-consultation) a good reference/case study.

The market consultation was developed particularly for OpenZaak. Turning this into a reusable template is hard, because we don't have any clear data points (ie another context in which we could do a market consultation) that will help us identify what elements are reusable. We could just strip mentions of 'OpenZaak', and copy over 98% of the text, but this doesn't feel very useful. We get the same value from just looking at the OpenZaak market consultation as a reference for our next iteration, and can always copy parts of it in the future. 

Moreover, cementing the current structure as template also cements a lot of legacy decisions in terms of structure, so that reworking (or refactoring) the current structure towards a reusable (configurable) structure might be more work than making a reusable core once we have done 2 or 3 market consultations for codebases. Therefore, this issue just addresses the smaller reusable units (ie the workshops). 

That being said, the learnings/reflections from the market consultation will be captured in blog posts, a learnings report, the product page, improvements to governance, and procurements from the public organization side.

**Comment by bvhme** [comment]
That sounds like a good idea. I like the idea of having an implementation already available for people to look at with the tools to do that.

I would be interested in making sure we have this as an 'activity' so that we build some language about when and how to deploy these tools. You can probably name this better than me, however here are some things I was thinking about: vendor ecosystem development or contributor ecosystem development.

**Comment by clausmullie** [comment]
Merged with #691 and #686
