### ISSUE TITLE
Add "Member" to the Glossary

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#688]
Derived from #660 

The term **Member** is currently missing from the [Glossary](https://about.publiccode.net/glossary/)

I propose to add the following:

**Member**:
A member is a wholly publicly owned organization that is officially part of, and able to govern, the Foundation for Public Code vereniging. They pay membership dues, vote in the general assembly, and help shape our processes by partaking in the governance and finance of our organization.
_Formal criteria:_ signed a membership contract, abides by our articles of association, pays yearly membership dues, and votes in the general assembly.

**Comment by bvhme** [comment]
Very good!

Can a member not decide not to vote in the general assembly?

Apart from that it can go straight in I think.

Perhaps we should mention we mean this as '*public member*' in used in the [articles of association](https://about.publiccode.net/organization/articles-of-association.html).
