### ISSUE TITLE
New member communications plan

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#692]
Have a plan to implement immediately each time a new member joins the Foundation.
This should live in [about/activities/communication](https://about.publiccode.net/activities/communication/).

It should include:

- an immediate response (eg updating [publiccode.net/members](https://github.com/publiccodenet/publiccode.net/issues/65), an announcement email to our mailing list and a tweet)
- a longer response that doesn't depend on the new member org (eg a blogpost announcing our exciting collaboration, focusing on specific codebases based on research we've already done)
- a longer response that does depend on the new member org (eg getting quotations from senior leaders, or setting out more detailed plans for what we'll do together in the months ahead) - agreed with the new member's communications team

**Comment by lscheske** [comment]
Great idea! Let's work on this together, @ElenaFdR

**Comment by ElenaFdR** [comment]
Boris steer: frame as vote of confidence in public code, validating our approach and raison d'etre (we appreciate their recognition that this supports their open source strategy), not emphasizing the effects this will have on our org.

**Comment by bvhme** [comment]
This doesn't need to be done all at once, and can be done in smaller iterations. Perhaps we can make a checklist out of the items in the issue?

Also, can this be the start of a `activities/member-onboarding`, so that we can keep that together and make sure those activities are shared between you?

**Comment by clausmullie** [comment]
@ElenaFdR some of this thinking may be useful for new partners joining, but I propose closing this issue for now as we are not doing member development.
