### ISSUE TITLE
Enable reporting in our repositories

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#693]
GitHub have a functionality to [enable a contributor to report disruptive content](https://help.github.com/en/github/building-a-strong-community/managing-reported-content-in-your-organizations-repository) in a repository. Since a few days, [this will show in the Community profile](https://github.blog/changelog/2020-06-23-community-content-reports-included-in-community-profile/) on the Insights tab of the repository. I suggest we enable that feature on all our repositories.

**Comment by bvhme** [comment]
I've enabled it in all of our high-use repositories! Good spot!

Closing as resolved :)
