### ISSUE TITLE
Non-Discrimination clause KBFUS

### ISSUE THREAD

**Issue by demkodo** [publiccodenet/about#696]
- Update Mission, founding principles and goals with Non-Discrimination.

From the KBFUS agreement: 

12. Non-Discrimination. The Organization has adopted a policy that it does not unlawfully discriminate on the basis of race, color, or national or ethnic origin in the administration of its activities, programs, policies and practices.

**Comment by lscheske** [comment]
I like this! I would expand this to be in line with the EU Charter of Fundamental Rights, so include: 

"Any discrimination based on any ground such as sex, race, colour, ethnic or social origin, genetic features, language, religion or belief, political or any other opinion, membership of a national minority, property, birth, disability, age or sexual orientation shall be prohibited."

**Comment by demkodo** [comment]
@lscheske this is great, thank you. I'm actually gonna use it as is :)

**Comment by ericherman** [comment]
To avoid taking on a maintenance debt, can we link to something, rather than copy-paste text from laws and policies that we follow and (for whatever reason) we wish to explicitly highlight?

**Comment by clausmullie** [comment]
Closed with #1050
