### ISSUE TITLE
Provisions Prohibiting Support of Terrorist Activities 

### ISSUE THREAD

**Issue by demkodo** [publiccodenet/about#697]
- To add to donation page:

G. Provisions Prohibiting Support of Terrorist Activities
1. Institution will not use any portion of any grant from the Fund to engage in, support or promote violence, terrorist activity or related training of any kind, whether directly through its own activities and programs or indirectly through its support of, or cooperation with, other persons and organizations engaged in such activities, and will take reasonable precautions and institute reasonable procedures to prevent any portion of the grant from being so used.
2. Institution certifies that: (a) we do not support violence or terrorist activities; (b) none of our trustees, directors, officers or key staff members support violence or terrorist activities and we do not employ any individuals known to us to support such activities; (c) none of our affiliates or subsidiaries support violence or terrorist activities, we do not engage in transactions of any kind with vendors, contracting organizations or any other entities known to us to support violence or terrorist activities, and we do not otherwise disburse any of our funds, as grants or in any other form, to individuals or entities known to us to support such activities; (d) we have reviewed the lists of individuals and organizations identified by the U.S. government, the United Nations and the European Union as associated with terrorism and we do not appear on those lists; none of our trustees, directors, officers, key staff members or other employees appear on those lists; and none of our affiliates, subsidiaries, vendors, other contracting organizations, grantees or other entities with which we engage in transactions appear on those lists.

**Comment by bvhme** [comment]
Do we need to publicly state this. I think we keep to the law and that makes these things illegal I'd say. That it's in the contract seems to be enough for me.
