### ISSUE TITLE
Describe what the role is of an advisor

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#70]
Now that we've started inviting people to be advisors, it might be great to point them to somewhere that explains what they should do and how.

**Comment by evanp** [comment]
Maybe an ADVISOR.md or just expanding the advisor section of the Contributing.md?

**Comment by ElenaFdR** [comment]
Closing because so far no potential members have asked for this; we'll reopen this when someone definitely tells us they would find this useful.
