### ISSUE TITLE
Update our community call video links to our own Jitsi

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#700]
Now that we have our own Jitsi server we should run our community calls on those. I suggest the following names:

- https://meet.publiccode.net/FoundationforPublicCode
- https://meet.publiccode.net/StandardforPublicCode

Those are simple enough to remember and descriptive enough what the calls are about. They could of course also be used for other meetings on those topics, which I consider to be an additional benefit.

An alternative simpler solution could be:

- https://meet.publiccode.net/CommunityCall

The downside would be that it might be confusing if we hosted community calls for other codebases but that problem would lie in the future.

Ping @AlbaRoza @ElenaFdR @bvhme

**Comment by bvhme** [comment]
I like the two links.

**Comment by ElenaFdR** [comment]
Does this proposal link to a previous proposal to have a Jitsi URL for each chat.publiccode.net channel? Those are currently aligned to [activities on About](https://about.publiccode.net/activities/).

**Comment by ElenaFdR** [comment]
Re the proposal above, my suggestion would be to have only 1: community calls. 
My reason is that the URL only needs to reassure people that they're clicking on the correct link to attend their meeting; a shorter URL is easier to skim. It also makes it easier for someone to type themselves, instead of havinig to cut and paste it. (For example, for someone using a smartphone in a not-very-integrated way, or opening the link on a colleague's computer).

NB: Jitsi URLs are not case sensitive. (I've just tested!)

**Comment by Ainali** [comment]
I think you make a good point. My only fear is that we have a couple of codebases under stewardship it might happen that one or two of those have their community call at the same time as us. Then it would be a tiny risk for confusion if ours are named with CommunityCall and theirs with the codebase name instead of them all going with the name. But that seems both somewhat in the future and also such a small risk so I don't feel strongly about it.

**Comment by demkodo** [comment]
Hi guys, I'm proposing to close this issue as we now have a separate Jitsi instance running for our community. Cheers, Deb

**Comment by Ainali** [comment]
The issue has not been solved yet. The call-in links on:

* https://about.publiccode.net/activities/community-calls/
* https://about.publiccode.net/activities/communication/running-community-call.html

still use Google meet links.

**Comment by demkodo** [comment]
Aha!! We are talking about the literal links in About!

**Comment by demkodo** [comment]
I'm gonna update the links then, and make it official, unless there's a reason not to?

**Comment by demkodo** [comment]
Updated it to: https://meet.publiccode.net/CommunityCalls

**Comment by AlbaRoza** [comment]
I believe we can close this one now, right @Ainali @demkodo ?

**Comment by Ainali** [comment]
No, the pages on about have not been updated yet. However, since we recently created an instance for our communities to use, my fear from June 29 is gone. Now we only need to decide if we want the URL in singular like my original proposal or in plural like @demkodo suggested October 22. Then we can make a PR with the change.

**Comment by Ainali** [comment]
Ping @ElenaFdR Should we change it quickly to https://meet.publiccode.net/CommunityCall So that we can use it for our last community call of the year next week or should we hold off to next year with any change?

**Comment by Ainali** [comment]
* https://meet.publiccode.net/FoundationCommunityCall
* https://meet.publiccode.net/StandardforPublicCode

These are the ones we *de facto* have been using the last couple of months. Should we just change our instructions to those?

**Comment by clausmullie** [comment]
Fixed with #828

I checked both the 'running a community call' files, and they both reflect the de facto ones we are using. As such, closing this issue :tada:
