### ISSUE TITLE
The activity Tool management is not linked from activities

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#702]
The page [Tool management](https://about.publiccode.net/activities/tool-management/) is not linked from Activities. I guess it has disappeared during some restructuring.

**Comment by demkodo** [comment]
It's is visible in here but just not (yet) pushed to develop, or so it seems. [Here it is visible.](https://github.com/publiccodenet/about/blob/develop/activities/index.md)

**Comment by ElenaFdR** [comment]
This was closed via #720.

**Comment by ElenaFdR** [comment]
(I needed to use something from /tool-management and got annoyed that it was hard to find.)
