### ISSUE TITLE
There is no mention of the documentation on documentation in the README

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#703]
In order to contribute, we can expect people to read the README of the repository, however, this doesn't point to the documentation we have on structure and content types.

Suggested solution: explain and highlight what you need to know in order to contribute to the `about` repository in the `README.md` file.

**Comment by bvhme** [comment]
Although sending on a bit of a detour, this would also resolve #66 as it would point people to the documentation on what the homepage of a directory is (the index).

**Comment by Ainali** [comment]
We need to add this somewhere, but should it go in the README or in the contributor guide for individuals?

**Comment by clausmullie** [comment]
How about linking in both the contributor guide (#1055) and the readme (#1056)  ?

**Comment by ericherman** [comment]
Linking from multiple places is fine. From a "where do I start?" or "what do I need to know?" I expect to start with the README to get an overview. If there are contributor guidelines, the README should link to or mention where these can be found. As we have a [CONTRIBUTING](https://github.com/publiccodenet/about/blob/develop/CONTRIBUTING.md) file as well as [two contributor guides](https://github.com/publiccodenet/about/blob/develop/contributor-guides/index.md), I suggest it is very possible that a contributor could reasonably start at any of these places, thus a bit of duplication may be justified.

Re-reading the README, on line 12 I see we link `CONTRIBUTING.md` twice, we do *not* link the contributing guides, yet we do link [how we structure our documentation](activities/documentation/index.md).

> We are looking for people like you to [contribute](CONTRIBUTING.md) to this project by suggesting improvements and helping develop the Foundation for Public Code. 😊 Get started by reading our [Contributors Guide](CONTRIBUTING.md) and [how we structure our documentation](activities/documentation/index.md).
