### ISSUE TITLE
Enhancements to our codebase governance diagram 

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#706]
While explaining [this page](https://about.publiccode.net/activities/supporting-codebase-governance/) on a call, two things came up.

- [ ] 1) The diagram refers to [municipalities](https://about.publiccode.net/activities/supporting-codebase-governance/governance-models.png), and perhaps should be 'public organizations'? 
- [ ] 2) The page doesn't link to our glossary items for users, maintainers, contributors, and end users, perhaps reducing the effectiveness of the diagram?

**Comment by clausmullie** [comment]
@Ainali what do you think about these two possible enhancements?

**Comment by Ainali** [comment]
1) Sure, a bit long in the graphic but that is more correct. Follow up on that: what about the word 'governments'?
2) I love hyperlinks -> more links!

**Comment by clausmullie** [comment]
1. Or just even 'organization' ?
