### ISSUE TITLE
Update Odoo cards with mails information

### ISSUE THREAD

**Issue by AlbaRoza** [publiccodenet/about#721]
For instance: there's a lot of useful information in the notes from calls @lscheske created after being introduced to some of our main stakeholders. Those notes were sent to most of the people working in the Foundation as mails, so that information would have to be moved to Odoo.

**Comment by ElenaFdR** [comment]
Try Odoo logging on the emails?

**Comment by felixfaassen** [comment]
@AlbaRoza we have a list of email aliases you can use to log email as notes for the appropriate cards so I think this issue can be closed. Or do you mean something else?

**Comment by Ainali** [comment]
I think it is more useful copying information only relevant to that organization to the associated card rather than forward the same email to several cards. The latter will make it a lot more work parsing was is relevant on each card.

**Comment by lscheske** [comment]
@AlbaRoza, we indeed use the Odoo logging function for the CRM Module. To log an email there you just have to CC/BCC or forward an e-mail directly to log-NAMEOFORG@publiccode.net. I think this functions similarly with the Projects module.

**Comment by AlbaRoza** [comment]
Yeah, and it was a thread of several mails, not sure if all of them were going to be included in Odoo

**Comment by Ainali** [comment]
Did no one read the original issue? It was about the weekly compiled emails that have compiled information relevant to several cards in Odoo. It makes no sense to forward it to three or four log emails. The lines in those emails that are relevant to put on a  card should rather be copied there or the cards will look spammy with mostly irrelevant information copied over several cards in just a few weeks.

**Comment by Ainali** [comment]
It looks like I'm the fool now when reading the original message again.

**Comment by AlbaRoza** [comment]
> It looks like I'm the fool now when reading the original message again.

I got what you wanted to said, @Ainali. However, my issue's intention was only to get the most important information of those mails into Odoo.

**Comment by AlbaRoza** [comment]
We can go on with what we have.
