### ISSUE TITLE
Resource for writing email FAQS - list of useful deep links

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#724]
At the opportunity stage of the membership funnel, Foundation people often have email exchanges with people at potential member orgs answering their specific questions with useful links. It would be helpful to have a cheat sheet to help write these emails more quickly.

(from communications assets for membership workshop, 23 July 2020)

**Comment by clausmullie** [comment]
I am going to close this issue as it's not currently a priority.
