### ISSUE TITLE
Create sample public code business cases ⭐

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#725]
At the opportunity stage of the membership funnel, people at potential member orgs often ask for material they can use to help build the business case within their org. Currently, we don't have materials ready to help them.

From: communications assets for membership workshop, 23 July 2020
Prioritized during dotvoting.

**Comment by clausmullie** [comment]
This issue is geared primarily towards members. Business cases for philanthropy are articulated in the case for support. @ElenaFdR can we close this issue?
