### ISSUE TITLE
Add links to live example pages from 'how to write a X' guides

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#730]
Looking at [how to write a resource](https://about.publiccode.net/activities/documentation/writing-resources.html), I found myself wondering if capitalization matters in frontmatter and wanted to go to a live page to see what we normally do.
Other people may have other reasons for wanting to look a at a live example, and it would be easy to add one.

**Comment by d80ep08th** [comment]
SO? Does capitalization matter then?

**Comment by clausmullie** [comment]
I did some looking in to this. Capitalisation does not seem to matter. In general we capitalise `index: Resource`, `index: Guide` and `index: Index`. I found an instance of the docusign resource which is not capitalised `index: resource` and it renders fine

**Comment by clausmullie** [comment]
#1070 #1071 #1072 to close this
