### ISSUE TITLE
Schedule periodic About reviews

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#743]
Review:
- the page updated the longest ago
- the highest traffic pages
- the lowest traffic pages
- user journeys from different users' perspectives: operations, a new codebase steward, a prospective member, someone impressed by a workshop we ran, a public code fan, someone worried about a legal or financial question (eg GDPR)
- a random URL picker

**Comment by Ainali** [comment]
In Plausible there is a view that can be useful for figuring out the highest and lowest traffic pages:

* https://plausible.io/publiccode.net/pages?period=6mo
