### ISSUE TITLE
Flesh out thinking for how we support SDG 16

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#758]
@lscheske says:
> I think there is also an argument to make about strong institutions - that by helping institutions retain full ownership over their software, it increases control and reduces reliance on proprietary solutions. In the long term, this strengthens institutions. Not an argument we need to include here for the purpose of the blog, but can as we develop this content further.

**Comment by clausmullie** [comment]
We have a [blog post on the SDGs](https://blog.publiccode.net/policy/2020/10/02/we-support-the-sustainable-development-goals.html) and a [list of the SDGs we support](https://github.com/publiccodenet/about/blob/develop/activities/value-and-impact/sustainable-development-goals.md).

In #755 the discussion states this page should remain to the point and factual. 

I therefore propose adding a word or two to the stub to reflect this thinking.
