### ISSUE TITLE
Add access to @bvhme's 'how we work' session for newcomers

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#768]
To do:
- [ ] Decide how that access is delivered (full team session, video, something else?)
- [ ] Update [how to staff](https://github.com/publiccodenet/about/blob/develop/contributor-guides/for-staff.md)

**Comment by bvhme** [comment]
Hey Elena, would we already like to do this for the upcoming 4 sessions, or for subsequent sessions?

**Comment by ElenaFdR** [comment]
@angelplasma would also like to see this!

**Comment by clausmullie** [comment]
@bvhme were these sessions recorded? Or shall I close this issue for now?

**Comment by bvhme** [comment]
No they weren't,  this was meant for new sessions. I suggest once we plan new ones we do them in the open.
