### ISSUE TITLE
Broken link in the review template

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#777]
In the file `activities/codebase-auditing/review-template.md` there is a link to the [Document maturity criterion](https://standard.publiccode.net/criteria/document-maturity.html) of the standard whose URL has changed in the recent release, this needs to be updated.

**Comment by Ainali** [comment]
Not only the link changed in the release, but we also split a criterion and updated the language and level of some requirements. Should these all go into separate issues, or should we convert this one into being updating this template in general?

**Comment by Ainali** [comment]
Fixed by #780
