### ISSUE TITLE
organization/staff is out of date

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#790]
@lscheske isn't on it at all, and the management section doesn't reflect our current structure.

**Comment by lscheske** [comment]
Good catch! We are still missing new roles for the Executive Team and haven't had discussions around what role titles should be.

**Comment by clausmullie** [comment]
This issue is now also out of date. 

Discussions on roles can be continued in #1036,  and new staff in #[212](https://github.com/publiccodenet/publiccode.net/issues/212), with staff removed via #1037 and [#224](https://github.com/publiccodenet/publiccode.net/pull/224).
