### ISSUE TITLE
Create course on the Standard for Public Code

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#792]
We have been offered to have a course about the Standard for Public Code hosted in the Academy that [OASC](https://oascities.org/) is launching next year. This issue aims to track the progress of it. The work is being done [in a Google Docs in their Drive](https://docs.google.com/document/d/1EId49bFi4nfXNmMRmXRocfT4meuYQyEVKH2o4B-yCzY/edit#) and OASC will be doing the actual implementation in their learning platform. We are doing video recorded introductions and quizzes to the sections listed below. We base the script on the sections 'Why is this important' and 'What this does not do'. Names after the section indicates who is working on it.

- [ ] Introduction videos
   - [ ] Public Code 
      - [ ] Video recorded (@nebster )
      - [x] Quiz (@Ainali)
   - [x] The Standard for Public Code 
      - [x] Video recorded (@bvhme )
      - [x] Quiz (@Ainali)
- [x] Code in the open (@Ainali)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Bundle policy and source code (@felixfaassen)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Create reusable and portable code (@Ainali)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Welcome contributors (@lscheske)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Make contributing easy (@ElenaFdR)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Maintain version control (@Ainali and @ericherman )
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Require review of contributions (@ericherman)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Document your objectives (@felixfaassen)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Document the code (@AlbaRoza)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Use plain English (@AlbaRoza)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Use open standards (@felixfaassen)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Use continuous integration (@ericherman)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Publish with an open license (@Ainali)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Use a coherent style (@ericherman)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz
- [x] Document codebase maturity (@lscheske)
   - [x] Script written
   - [x] Video recorded
   - [x] Quiz

**Comment by lscheske** [comment]
Suggest to add a section that describes the course itself including: 
* Goal of the course
* Who it is made for (audience)
* Learning objectives & outcomes

**Comment by Ainali** [comment]
> Suggest to add a section

I'll check, but I think that is handled 'outside' of the course - in the learning platform before starting the course. But yes, the content still needs to be created even though it might not be a section of the course.

**Comment by bvhme** [comment]
I'd be up for doing the introductions on public code and the Standard for Public Code, but when do these need to be produced by? I need to see if I can plan that.

**Comment by Ainali** [comment]
> I'd be up for doing the introductions on public code and the Standard for Public Code, but when do these need to be produced by? I need to see if I can plan that.

By mid January would be great. You don't need to rush them before the end of the year.

**Comment by lscheske** [comment]
I've written the script and made the quiz for "Welcome Contributors". Would be great if someone could review so that I can record the video (in January).

**Comment by AlbaRoza** [comment]
@ElenaFdR Looks like you had signed up for "Use plain English".

Last week I did it myself because I was keeping the Drive document as reference and didn't know you selected it previously, apologies!

**Comment by ElenaFdR** [comment]
Good to know, @AlbaRoza! Would you collectively like me to pick up one of the others that's currently unassigned?

**Comment by AlbaRoza** [comment]
Yeah @ElenaFdR, please feel free to choose another one! Just put your name here and I'll keep an eye here next time before focusing in another point of the criteria.

**Comment by bvhme** [comment]
I don't know who this should go to but here's my video for you to download: https://drive.google.com/file/d/1yQkKlzejc3gMNhQJ9YEzMLw-oRFgB1ra/view?usp=sharing

It's very much the first version and thus didn't bother going beyond 1080p. Let me know what needs to be better and I can see if next week I can make some time to improve this. I had a lot less time for this than I wanted (of course).

**Comment by bvhme** [comment]
And if there are bigger issues I can make time this afternoon to solve it!

**Comment by Ainali** [comment]
I'll look at it at once!

**Comment by bvhme** [comment]
And I've compressed a version for YouTube: https://drive.google.com/file/d/16g9Obpwu0UVEeih97RjAJ0QhH_0CtEwP/view?usp=sharing

**Comment by Ainali** [comment]
The course is now published at: https://citybycity.academy/course/standards-for-smart-cities
Let's continue with follow-up improvement in separate issues.
