### ISSUE TITLE
Publish case for support

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#794]
I'm disaggregating publishing the case for support and #785. 

Still to do on the case for support:

- [x] @felixfaassen and @ElenaFdR to craft bio
- [x] @angelplasma to update case for support:
 1.  Add @felixfaassen bio
 2. Synchronize content between A4 and Letter sizes
 3. Add content index + page numbers
 4. Export both sizes as PDFs
- [x] upload case for support in PDF to https://about.publiccode.net/activities/philanthropic-fundraising/
- [ ] link to case for support from organization/philanthropy.md (after #786) and philanthropic-fundraising/index

**Comment by lscheske** [comment]
I went through the CfS yesterday and noticed a few other things: 

* Add a quote from Stewart (There's currently a placeholder for it)
* Codebase content in the end could be updated with the codebases we are actually stewarding (i.e. add OpenZaak and add Signalen content)
