### ISSUE TITLE
Update codebase steward activities and resource related to product marketing and product management

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/about#795]
In doing our codebase stewarding work we gradually learn more about the work involved on the product side of a codebase.
In the light of this we may need to update the activities, descriptions and resources related to codebase stewarding for product marketing / product management.

We also created some additional assets which need to be included in the toolbox so other codebase stewards are able to utilize these assets.

- [x] Rewrite codebase activities related to product marketing / product management based on our thinking an draft outlined here: https://hackmd.io/-Iu3Z2yETGaspAHUF9oscA
- [x] Put draft on Github about
- [x] Change Product Marketing into "Product" and explain product marketing activities and product management activities
- [x] Review existing assets and resources and tools and update documentation
- [x] Include [https://github.com/publiccodenet/product-steering](https://github.com/publiccodenet/product-steering) repository template
- [x] Schedule review with codebase stewards
- [ ] Schedule communication review with @ElenaFdR 

- [ ] Optionally write blogpost about "Product Management in Public Code"

**Comment by bvhme** [comment]
Great to see this.

I would recommend steering very clear of the idea of and word 'product management'. I've experienced it as something people try to latch onto to offload responsibilities to us and to centralise decision making.

**Comment by AlbaRoza** [comment]
Referenced in / about #642
