### ISSUE TITLE
Make a list of ok licences for us to publish under

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#802]
[Our founding principles](https://about.publiccode.net/organization/mission.html#founding-principles) say:

> We publish under licenses approved by the Open Source Initiative or Creative Commons licenses that do not limit commercial reuse.

At the moment, we scramble to identify an acceptable licence each time we publish our content on a new 3rd party platform (for example our recent publication of our Creative Commons Global Summit workshop video on YouTube).

Since none of us are professional experts in open licenses, it would be helpful to add a short list of licenses we commonly use **and why** (insteaad of other similar ones) somewhere to About, so we're not doing original research each time.

**Comment by Ainali** [comment]
I think that is a great suggestion! My suggestion is:

1. [CC 0](https://creativecommons.org/publicdomain/zero/1.0/): Because it is the least restrictive license and we want to enable as much reuse as possible.
2. [CC BY](https://creativecommons.org/licenses/by/4.0/): Only on platforms where it is not possible to use CC 0 (for example YouTube).
3. [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/): Only on platforms where CC 0 or CC BY is not possible to use (none known).
4. [CC BY-ND](https://creativecommons.org/licenses/by-nd/4.0/): Only to be used where we absolutely don't want anyone to change the material, but still be able to use it and share it. This use case is probably only hypothetical.

**Comment by ElenaFdR** [comment]
Re 4. CC BY-ND: what about when we've included photos of real people we know participating in workshops?

**Comment by ElenaFdR** [comment]
(We should also, of course, update our photo consent to say which licences we distribute under.)

**Comment by Ainali** [comment]
> Re 4. CC BY-ND: what about when we've included photos of real people we know participating in workshops?

There are several laws covering what you may or may not do with photos of real people. Copyright should not be used as a tool to try to enforce those. With that said, we should probably also have clear and helpful guidelines that helps us navigate those considerations.

**Comment by bvhme** [comment]
Great. I'd say the solution here should be guidance on what license to choose, as the lists of licenses can best be found at the Open Source Initiative and Creative Commons.

My proposal for the guide building on the 'open by default and welcoming contributions' founding principle:

License to use: [CC0 - Public Domain](https://creativecommons.org/share-your-work/public-domain/cc0)
Exception: content needs to be guaranteed to be unaltered after publishing by us: [CC-BY-ND](https://creativecommons.org/licenses/by-nd/2.0/)
Exception: brand assets or trademarks: No license

It's also good to note here that none of these licences cover the right of portraying someone on photographs (Droit à l'image, Portretrecht, Recht am eigenen Bild) or falsely identifying as others, those are not copyright issues and thus cannot be solved with licenses.

**Comment by bvhme** [comment]
Ow, my comments and Jan's crossed each other. I think they can combine neatly. :)

**Comment by Ainali** [comment]
A follow up question, where would it make sense to put this guidance? Does it fit under Communication or Documentation or is it its own activity? Or is this perhaps under [How to staff at the Foundation for Public Code](https://about.publiccode.net/contributor-guides/for-staff.html) or a link from [Cultural values](https://about.publiccode.net/organization/cultural-values.html) under Organization?

**Comment by bvhme** [comment]
I feel that 'how to staff' seems most logical, as this really applies to so much of people's work. However if it is too meaty for that it might have a better home in communication.
