### ISSUE TITLE
Create toolbox template for codebases

### ISSUE THREAD

**Issue by AlbaRoza** [publiccodenet/about#809]
Required skillsets to nurture a codebase from all the possible disciplines: Product Management, Policy Makers, Software development, UX, etc.

**Comment by clausmullie** [comment]
This has been marked as done in the kanban. The toolbox has been created, but cannot currently be made open as it contains personal information. @Ainali and/or @ericherman is cleaning up the toolbox and opening it up something we want to prioritse now? Or can this issue be closed?

Work from the product management angle was contributed via #814

**Comment by ericherman** [comment]
I think we should close this until we have desire to re-use it, then we can invest in cleaning it up to get a head-start.

**Comment by clausmullie** [comment]
Ok, sounds good!
