### ISSUE TITLE
Migrate mailing list/community call sign up to Odoo survey

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#813]
Today we use Google forms for letting people sign up to our mailing list: https://forms.gle/gn7wR2Eaxbv5g1BF9

We now have the Odoo survey app installed that could be used instead. A test is available at: https://odoo.publiccode.net/survey/start/594b9243-c7e5-4bc1-8714-35137c971842

To switch tools would be nice since it features our URL, we have more possibilities for styling and we are using FOSS as an initial contact point with our community.

Things that need to be updated when doing the switch:

- [x] links in [footer](https://github.com/publiccodenet/jekyll-theme/search?q=forms.gle)
- [x] links in [About](https://github.com/publiccodenet/about/search?q=forms.gle)
- [x] links in the [blog](https://github.com/publiccodenet/blog/search?q=forms.gle)
- [x] document the process for taking care of the responses

**Comment by demkodo** [comment]
@Ainali and @ElenaFdR will write up guidance on this topic

**Comment by Ainali** [comment]
Everything is fixed now!
