### ISSUE TITLE
Tests: 400 errors from Twitter

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#825]
So, Twitter is breaking our testing by sending 400 errors to html-proofer in Travis. Turns out Twitter has completely stopped sending HTTP codes that can be used by non-modern browsers, as when I use `curl` on my computer I get a 200 for any URL (wrong ones as well) with a body that this browser is not supported and 400 when I use `wget`.

So all in all, it is impossible to chech whether a URL on Twitter exists from htmlproofer or the command line.

**Comment by ElenaFdR** [comment]
@bvhme suggestion made in discussion: let's not link to Twitter, at all. We can either create a Wayback Machine archived page for any tweets where we care about the content, or just write out handles in plain text (for people to seek out themselves).

**Comment by Ainali** [comment]
Letting some tools deciding what content we should have seems like a sorrowful approach, especially if it leads to making the user experience on our website to be poor. However, linking to an archived tweet is not a bad idea since the original tweet might be getting deleted. But I suggest we avoid writing a Twitter handle in plain text and instead use a better link, or just use the full real name of the person/organization instead without implying burden on the reader.

**Comment by bvhme** [comment]
@ainali, I think this is where policy for canonical (about/standard) and ephemeral content (blog/a project) diverge. For canonical sources we want to link to content (which in this case would mean being able to check whether it still exists) where for ephemeral it is only important that content exists when it is published.

So my recommendation is to use archived links for content linked in canonical sources on sites that don't support us checking the existence of it.

In this case that would mean, link to tweets on twitter in the blog, don't in `about` unless the content is important in which case we can use an archived link.

**Comment by ElenaFdR** [comment]
## Documentation

HTMLproofer now ignores Twitter links on:
- blog.publiccode.net (assuming that any Twitter links are ephemera)
- publiccode.net (assuming the only Twitter links are in team bios)

We've decided to link only to archived pages, not Twitter, for these repos (HTMLproofer checks Twitter links on these repos):
- about.publiccode.net
- standard.publiccode.net

No changes have been made to any other repos (eg Governance Game, Projects, Illustrations, Smart Cities? Public Code!)
