### ISSUE TITLE
Policy Plan: 4.1 Fundraising - contradictory content

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#826]
There is contradictory content in section 4.1 of the [Policy Plan](https://about.publiccode.net/organization/policy-plan.html).

The last sentence states "Please note that the Foundation for Public Code will not actively pursue donations and gifts and will spend no or very limited time on fundraising (not more than 5% of its budget)." 

This sentence is contradictory as it states on the one hand that we do not actively pursue gifts and donations, and then says we spend only limited time. Which is it? 

In reality our President does do this actively. I suggest to change this to something along the lines of: 

"Please note that the Foundation for Public Code only spends limited time on fundraising (no more than 5% of total annual budget)."

**Comment by ElenaFdR** [comment]
"The Foundation for Public Code will not actively pursue donations and gifts" was accurate when we wrote this - it was written to reassure potential members.
A more accurate statement now is:
"Please note that the Foundation for Public Code spends limited time on fundraising (no more than 5% of total annual budget)."

**Comment by clausmullie** [comment]
I am going to close this issue. These are valid observations, but my sense is that the policy plan is a static document which was adopted and should not be edited retrospectively. 

>This policy plan was adopted at the 23 August 2019 board of directors meeting and approved by the general assembly.
