### ISSUE TITLE
Policy Plan: 4.2 Asset Management - confusing sentence & unclear link to 4.1

### ISSUE THREAD

**Issue by lscheske** [publiccodenet/about#827]
See also issue #826 

* Section 4.2 of the Policy Plan starts with a sentence that mentions only membership dues, but makes no mention of the gifts/donations mentioned in the previous section (which are currently, and for the duration of this policy plan at least - now until 2022 - the clear majority of our income). We should add a line that says how we manage those assets as well. This should be in line with the updates made for philanthropic giving #672. 

* The second sentence is wordy and unclear. "In order to ensure the continuity of the association and its work (especially since we specifically focus on putting codebases on sustainable footing), we have a financial objective to keep enough financial reserves to find viable alternative stewardship for public code that organizations rely on. In practice we expect to not keep more than the cash equivalent of 36 months’ of projected costs in the association’s bank account."

This doesn't say much about how the assets are being managed. We might want to rethink the 36 months projected costs on our bank account, as we are consistently working towards extending our runway (through membership dues, but also donations).

Could this be clarified and rewritten? E.g. along the lines of:
* Our financial objective is to ensure sufficient assets that allow for continuity of the association and its mission.
* We will not retain more assets than is reasonably necessary (determined by the board of directors) to guarantee the continuity of the association's work in pursuit of its statutory goal as referred to in article 2.1.

**Comment by clausmullie** [comment]
I am going to close this issue. These are valid observations, but my sense is that the policy plan is a static document which was adopted and should not be edited retrospectively. 

>This policy plan was adopted at the 23 August 2019 board of directors meeting and approved by the general assembly.
