### ISSUE TITLE
Create a certificate of completion for the Standard course?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#841]
It's possible to [Create a certificate of completion](https://support.learnworlds.com/support/solutions/articles/12000003618-create-a-certificate-of-completion) in the course platform that will be automatically issued to people who complete [the course](https://citybycity.academy/course/standards-for-smart-cities). Settings that can be made is if they:

- need to complete the questionnaires only or all the learning units (I suggest the latter)
- can share to LinkedIn, Twitter or Facebook (I suggest all three)

And then we need to design a custom PDF certificate that they can download.

Are there any arguments to not do this or should we set it up?

**Comment by AlbaRoza** [comment]
Really like this!!

**Comment by Ainali** [comment]
Here is a [very rough draft](https://collaboration.publiccode.net/nextcloud/index.php/s/qFrXp8zeLB5XBj3) of a certificate. Do we want some flair to it?

**Comment by lscheske** [comment]
I like it! Do we want to use the word award? It's hardly an award. I would also add what it is they completed (e.g. online course)

Certificate of Completion
Madeup Namesson
has successfully completed the free online course
Introduction to the Standard for Public Code

**Comment by Ainali** [comment]
I just copied the wording of the template :)
But I do like putting it in active tense, i.e. that "This X (document?) certifies that"
If we go with "Certificate of Completion" I would like to put that in a larger size than the name, to give it the authority it aspires for.
I don't like the word "free" I think that only devalues the certificate. We could go with "open" if it is the license we want to highlight.

**Comment by Ainali** [comment]
Yes, I agree that just that is important. Is there some other small print we would like to add to make that clear? Or can we state it in some other nice way? It's a subtle balance, because if we add too much of it, it also discourages people sharing it with the world. (Which I think where we can get most value out of issuing these certificates.)

**Comment by lscheske** [comment]
How about:

CERTIFICATE OF COMPLETION
This certificate is awarded to
Madeup Namesson
for successfully completing the open online course
Introduction to the Standard for Public Code

We might have to add the OASC & CityXCity Academy logos too, what do you think?

**Comment by Ainali** [comment]
Perhaps we can even leave out "successfully"? It's kind of implied anyway.

While I don't think we *have* to add those logos, I feel it's a good idea.

**Comment by Ainali** [comment]
[Here is a new suggestion](https://collaboration.publiccode.net/nextcloud/index.php/s/dB9XQw6bpN6xjYE). Obviously, we need to check with OASC if including the logos is okay with them before moving on:

**Comment by Ainali** [comment]
I got an okay on the design from OASC!

**Comment by Ainali** [comment]
This has been implemented (and tested by me and Eric).
