### ISSUE TITLE
The Gitflow explanation we link to now recommends a different explanation

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#843]
There's a new [callout at the top of the page](https://nvie.com/posts/a-successful-git-branching-model/).
Should we update our preferred explanation as well?

**Comment by Ainali** [comment]
As it now recommends different flows if it is versioned & deployed in contrast to being delivered as a web service, yes, we should probably also make that distinction.

**Comment by d80ep08th** [comment]
Whats your preferred explanation then ? or do you have a link to the explanation you prefer @ElenaFdR ??
