### ISSUE TITLE
Update privacy policy to include Plausible

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#854]
@felixfaassen added Plausible to our websites via [Jekyll PR 65](https://github.com/publiccodenet/jekyll-theme/pull/65), so we need to update our privacy policy to make explicit that we use Plausible.
We should also update our tool management.

**Comment by demkodo** [comment]
@ElenaFdR where and what in the policy does need this update? There is already a link pointing to our tools management page, thus also to Plausible. But, if it needs to be more explicit here, let me know

**Comment by ElenaFdR** [comment]
Is "[The Foundation strongly supports individuals’ right to privacy. For this reason we don’t have an analytics package that tracks individual users on any of our websites](https://about.publiccode.net/organization/privacy.html)." still true given our use of Plausible? I *think* so.

**Comment by felixfaassen** [comment]
Here is information on how we count users: https://plausible.io/data-policy. I think we should use the word counting, we do not track users as that suggests we "know" individual users. So may be we could re-write and say we use plausible to count users anonymously and refer to the policy link of plausible?
