### ISSUE TITLE
Update article 32 Articles of Association: end date of fiscal year in Spanish version 

### ISSUE THREAD

**Issue by demkodo** [publiccodenet/about#861]
The Spanish version has the wrong date in article 32. The end date of our first prolonged fiscal year was 31 December 2020 not 2021. https://about.publiccode.net/organization/articles-of-association.es.html

**Comment by demkodo** [comment]
The sentence: 'El primer ejercicio económico termina el treinta y uno de diciembre de dos mil veintiuno." has now been updated with the correct year.

**Comment by AlbaRoza** [comment]
Solved in here: https://github.com/publiccodenet/about/pull/863
