### ISSUE TITLE
Consider documenting learnings on 'closing the loop for open requests'

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#874]
We had some good discussions between staff we thought may be good to document. I will park them here as an issue, as I don't have a clear sense of where to add them to about. 

If this issue isn't picked up within 2 weeks, we can close it.

## Questioning video-call as default. 

This is definitely down to individual preferences, but video calls are more taxing on the eyes and require more points to pay attention to. 

Some people on the team found that when having 1-on-1 check-in calls or chats, doing it over a phone call while walking around outside worked just as well (or better) and was less taxing/tiring. 

## 'Closing the loop' on open-ended requests.

We identified a potentially harmful patterns around open requests not being 'closed'. 

So for example, someone sends an open ended request for input or help or review, but doesn't hear back from anyone.

This can be demotivating for the initiator (feeling of shouting into the void, not being taken seriously, valued or respected, and feeling like doing meaningless work), expensive for the organisation (many people reading, thinking about it, closing, opening it later again, without coming to a conclusion), and a cycle of the item resurfacing without resolution.

While this loop is easily closed in a collocated working environment (reach over and say hey), a remote environment makes this more tricky.

We identified several ways to mitigate this by trying to get a culture around:
1) Don't deprioritise with silence, but actively say you can't/won't prioritise something
2) Set a deadline for responses, and signal what you will do after that deadline (move ahead, or stop working on it if no other interest,...) 
3) Signal clearly if/when this is a blocker to your work that prevents you from moving on
4) Where possible ask individuals for input over an undefined group 
5) Where possible, provide clear context, aims and expectations around the request
6) When you take on an open request, try signal whether it is something you will prioritise, or something you will do *if* you have time and space

**Comment by Ainali** [comment]
Yes, I think these are findings that are important to document and share within the organization. It can reduce a lot of frustration and make us more efficient.

**Comment by ElenaFdR** [comment]
I really like these; they're a good reminder.

**Comment by clausmullie** [comment]
Closed with #886
