### ISSUE TITLE
Add information about how we stay GDPR compliant when collecting details for newsletter etc

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#893]
A really good comment from @ElenaFdR in #890
> add info somewhere that this approach keeps us GDPR compliant because we have a record showing that we have someone's contact details by their consent (#350).

**Comment by clausmullie** [comment]
We now have 
* [mailing list instructions](https://github.com/publiccodenet/about/blob/develop/activities/tool-management/mailing-lists.md) which link to a privacy policy, and explain how we unsubscribe and can remove data if requested
* [privacy and GDPR policy](https://github.com/publiccodenet/about/blob/develop/activities/tool-management/odoo.md) of where we store our data

@Ainali can I get 
1) your consent for closing this issue?
2) your second opinion on whether it closes this issue as well #350
Thanks!

**Comment by Ainali** [comment]
Yes, I think this is enough to close both issues.
