### ISSUE TITLE
Add expectations to podcast guest instructions

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#907]
We have had a few invited guests that seem to be under the impression that it would take a lot of time to be a guest on our podcast. We should be explicit in our first contact how little time this will take for them. Add a line to the [instructions](https://about.publiccode.net/activities/live-streaming/prepare-live-stream.html) so that we remember to include it.

**Comment by AlbaRoza** [comment]
Good one! I thought of this when I sent some e-mails earlier today :)
