### ISSUE TITLE
Missing articles mentioning the Foundation or our work

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#916]
To add to `activities/value-and-impact/all-press.md`:

https://os2.eu/blog/ny-release-af-standard-public-code

**Comment by ElenaFdR** [comment]
Also add: https://www.dxw.com/2020/02/creating-new-collaborative-organisations-to-operate-shared-services/

**Comment by ElenaFdR** [comment]
VNG references:
- [OpenZaak case study](https://commonground.nl/news/view/752192c5-7222-4769-a738-de47dfcfb6f5/openzaak-van-samen-organiseren-naar-samen-realiseren) (23 Feb 2021)
- [Common Ground report, Q1 2021](https://publicaties.vngrealisatie.nl/commonground/2021/1/)
- [Signalen case study](https://commonground.nl/news/view/2a13308d-872e-4b98-8dff-d4d3bcb36586/steeds-meer-gemeenten-maken-gebruik-van-signalen) (28 April 2021)

**Comment by clausmullie** [comment]
Fixed with #970, didn't autoclose
