### ISSUE TITLE
Include section on 'how to implement standard in your organisation'?

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/about#923]
Might be useful to give people who come across the standard a set of actions they can take to start implementing it in their organisation. 

This could include:
 * How to get started on a small scale
 * How to make the business case (required investment, return on investment, etc)
 * What operational workflows they could use to mainstream it in their organisation
 * How to mandate it into procurement
 * A way to contact other organisations that have implemented the standard

**Comment by ericherman** [comment]
How-to guides, case studies, examples to copy, educational material, etc are better placed outside of the standard. These items would be great on About or maybe even as an OASC course.

**Comment by clausmullie** [comment]
I'm going to close this issue for now. This may become a priority again in the future, in which case the work would benefit from a more specific and detailed issue than this outdated and superficial one.
