### ISSUE TITLE
Graphic only works on white, a potential risk in future reuse

### ISSUE THREAD

**Issue by demkodo** [publiccodenet/about#944]
From annual report PR #933  - Pertaining [to this image](https://raw.githubusercontent.com/publiccodenet/about/annual-report-2019-2020/organization/annual-reports/images/80per-people.png).

**Comment by clausmullie** [comment]
I will close this issue as part of housekeeping. The annual report was merged, the image linked is 404 and the issue signals a potential future risk. At this stage, I think we can solve this when it becomes an issue again.
