### ISSUE TITLE
Create a canonical list of organizations we have some formal relations with

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/about#946]
The [annual report](https://about.publiccode.net/organization/annual-reports/annual-report-2019-2020.html#our-ambitions-for-the-next-year) sets out plans to embrace non-membership partnerships in the coming year. As part of eventually reflecting this in a prominent way on publiccode.net, I'd like an About resource listing all of orgs we have some relationship or partnership with plus either a link to the partnership agreement, or at least some description of what's been agreed.
(For example, I have a copy of the OW2 partnership agreement in my email inbox, but that's hardly accessible or transparent.)

**Comment by ElenaFdR** [comment]
Friendly orgs with formal relations I'm aware of so far:

- OW2 (MoU)
- OASC (MoU)
- OSPO Alliance (we're founding members)

**Comment by Ainali** [comment]
Decidim Association is an affiliate since 2019-12-19.

**Comment by lscheske** [comment]
Is this *finally* the simple solution that was attempted in #660 #687 #689 and others?

**Comment by Ainali** [comment]
Just to note that partnerships were fixed by #1025, so what remains for this issue is affiliates.
