### ISSUE TITLE
Develop and implement a badge "stewarded by foundation for public code" 

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#974]
Design a badge that communicates that a codebase is "Stewarded by the Foundation for Public Code".

Reasoning:
We would rather have a badge in a footer instead of logo's in headers amongst other collaborators of a codebase, as it would more accurately reflect the way we steward it. We are more of the infrastructure for the codebase than being a driving partner.

- [x] Design badge
- [x] have a hosting location for image
- [ ] Remove logo from Signalen.org
- [ ] Remove logo from OpenZaak.org
- [ ] Remove logo from Demodam.org
- [ ] Add badge in footer to Signalen.org
- [ ] Add badge in footer to OpenZaak.org
- [ ] Add badge in footer to Demodam.org

**Comment by Ainali** [comment]
First rough sketches on a badge just to explore some possibilities. 
![badge sketches](https://user-images.githubusercontent.com/5566159/131300093-e739cdfc-f9d0-4123-8ac2-d38b1ab16410.png)

**Comment by angelplasma** [comment]
Sounds like a solid idea, @Ainali! I've made some initial variations, attached below.

**Questions:**
1. Would we be comfortable with shorter phrases, or even something very concise like "Public Code"?
2. Should this definitely be a free-floating graphic, or something that attaches to the edge of the window?

Working file here (which should move to a more appropriate place, like @bvhme's more official logo file in Figma): https://www.figma.com/file/Mcz4evZVI4rRwv3quXtKGC/Site-Map-Wireframe-exploration-Foundation-for-Public-Code?node-id=1303%3A1667

<img width="1687" alt="Stewardship badge v02" src="https://user-images.githubusercontent.com/6484164/131390158-a16e1419-e280-424d-98c2-1128ea815a60.png">

**Comment by Ainali** [comment]
Very nice! And excellent questions! For 1. I think that, even though the badge in general are more beautiful with less text, we want a bit of a blurb here since this might be the only information about us on the pages this is shown (since we imagine this could be used in the footer of a site). 

And for 2. I think we at least need a version that can function as a free floating graphic, since we will not be in editorial control of the sites that the badge gets used on.

**Comment by felixfaassen** [comment]
@angelplasma Nice work! I really like the third badge from the left  in the top row (and the variant).  I think one of the important aspects of the badge is show people that we steward this codebase and that people who are interested in what that means can look that up,  I agree with @Ainali.  Also nice idea to make a floating one!

**Comment by Ainali** [comment]
Related is also the question of where should this badge link to? There are a few alternatives:
1. The specific codebase overview on publiccode.net, example: https://publiccode.net/codebases/signalen.html
2. The page on stewardship on publiccode.net: https://publiccode.net/codebase-stewardship/
3. The page on stewardship on about.publiccode.net: https://about.publiccode.net/activities/codebase-stewardship/

Separately, since we have plausible, we should probably use something like ?utm_medium=badge&utm_source=signalen.org in the link.

**Comment by Ainali** [comment]
> Should it be "one size fits all" or should it be "case by case" or are there three or four "known use cases"?

I'm thinking that the link *type* should be universal, but if we go with the specific codebase overview it will obviously be unique links for each codebase's badge. 

> 
> > Separately, since we have plausible, we should probably use something like ?utm_medium=badge&utm_source=signalen.org in the link.
> 
> Does this suggest the need for some level of case-by-case customization, regardless?

Yes. Perhaps the utm_source is overkill for our codebases, since I guess they'll pass along the referrer anyway, but I see no reason why we should not add it. It'll still be separate pull requests to each codebase to add the badge and the link, so we don't *have to* find a code snippet that works universally.

**Comment by Ainali** [comment]
Trying to move this forward. Since @felixfaassen liked the third one from the left (and I do too), @angelplasma can you finalize the design of that one and upload the files to the [brand repository](https://github.com/publiccodenet/brand)?

**Comment by ericherman** [comment]
I, too, like the rounded one more.
