### ISSUE TITLE
Add README at the organization level

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/about#987]
Since a few weeks, it's possible to add a README file at the organization level. We should add one that gives an overview of our repositories. 

https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/

**Comment by Ainali** [comment]
I suggest we add a short section that explains who we are and why we do what we do. This gives people a little more context to our repositories without needing to navigate away, while keeping this to as little text to maintain as possible.

**Comment by clausmullie** [comment]
Sounds good. We could also do some tweaking to the repository subtitles to make them more informative. Some of them are a bit stub like at the moment.

**Comment by Ainali** [comment]
If we want to, we can also add a nice header image to it to give it some flair. I think the hand with the ball illustration would be delightful.

**Comment by Ainali** [comment]
We have now created a minimal first iteration. The repository is available at https://github.com/publiccodenet/.github
