### ISSUE TITLE
The comma in the Codebase Steward titles makes using it in running sentences cofusing

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/about#99]
I would suggest finding something that is more natural for use in common language, for instance replacing the comma with the word __'for'__ in running text, or everywhere.

@nebster @clausmullie, input?

**Comment by clausmullie** [comment]
I agree. Alternatives could be Codebase Steward (Quality), Codebase Steward : Quality or even Quality Steward, Community Steward, Product Steward, Support Steward?

**Comment by bvhme** [comment]
Hmmm, I hadn’t thought of ‘Codebase _____ Steward’ yet, that does work
quite naturally. I think adding any kind of punctuation to these titles
makes them hard to deal with.

**Comment by ElenaFdR** [comment]
We agreed on 'Codebase Steward for _____', and have made this change throughout.
